# visual studio code = Plain text -> python (보기 편함)
# Notepad++ = Normal text file -> P -> Python (보기 편함(?))

# 본 문서는 CC BY-NC-SA 2.0 KR에 따라 이용이 가능합니다.
# https://creativecommons.org/licenses/by-nc-sa/2.0/kr/

# version = [ 1.0.0d release ]

options:
	# 카린봇 Original Setting
	# a부터 z까지 단일 알파벳 = 접두사
	
	a: &f[ &eTL &f] 
	b: [ ! ]
	c: &f[ &a! &f]
	
	# skycloudscid = 하늘구름 공지사항 채널 아이디
	# lucascid = 루카스 공지사항 채널 아이디
	# botonoff(0~100) = 봇의 온오프 메세지가 전달될 채널 아이디
	# log = 로그 채널
	# karinid = 카린 디스코드 아이디
	
	skycloudscid: 711431778098872406
	lucascid: 696689315811426314
	botonoff0: 694153082506051614
	log: 714630863089959063
	karinid: 624274923455512577
	glog: 713968917403664454
	
	# token = 카린봇 토큰
	# name = 카린봇 이름
	
	token: your token
	name: KaRin Bot v2

On script load:
	set {openserver} to 3
	login to "{@token}" with the name "{@name}"
	send "{@c} &b카린봇 &e로드 &a성공&f!" to console
	set {krbpremium::624274923455512577} to true
	set {krbpremium::451335803038203904} to true
	delete {naruto}
	delete {token}
	
On skript load:
	#login to "{@token}" with the name "{@name}"
	set {krbpremium::624274923455512577} to true
	set {krbpremium::451335803038203904} to true
	set {_uptime::s} to 0
	set {_uptime::m} to 0
	set {_uptime::t} to 0
	set {_uptime::d} to 0
	set {automark} to 0
	set {개발자게임} to "개발"
	create embed:
		set title of the embed to "ON"
		set the colour of the embed to GREEN
		set the description of embed to "카린봇이 켜졌습니다."
		set the footer of embed to footer with text "KaRin Bot Engine by IHAH"
		send last created embed to channel with id "{@botonoff0}" with "{@name}"
	
on skript unload:
	send "{@c} &b카린봇 &c언로드 &a성공&f!" to console
	create embed:
		set title of the embed to "OFF"
		set the colour of the embed to RED
		set the description of embed to "카린봇이 조금 뒤 꺼집니다."
		set the footer of embed to footer with text "KaRin Bot Engine by IHAH"
		send last created embed to channel with id "{@botonoff0}" with "{@name}"

every 20 ticks:
	if {jumgum} is true:
		mark "{@name}" as playing "현재 카린봇이 점검중입니다!"
	add 1 to {_uptime::s}
	if {_uptime::s} is 60:
		set {_uptime::s} to 0
		add 1 to {_uptime::m}
	if {_uptime::m} is 60:
		set {_uptime::m} to 0
		add 1 to {_uptime::t}
	if {_uptime::t} is 24:
		set {_uptime::t} to 0
		add 1 to {_uptime::d}

every 10 seconds:
	if {jumgum} is not true:
		add 1 to {automark}
		if {automark} is 1:
			mark "{@name}" as playing "HomePage | http://karinbot.new.so"
		if {automark} is 2:
			mark "{@name}" as listening "[ 카린아 도와줘 ]"
		if {automark} is 3:
			mark "{@name}" as playing "Version | %{version}%"
		if {automakr} is 4:
			mark "{@name}" as playing "개발자는 %{개발자게임}%"
			set {automark} to 0
	else:
		mark "{@name}" as playing "현재 카린봇이 점검중입니다!"

command /카린봇관리자 [<integer>]:
	trigger:
		if arg 1 is set:
			set {mcusername} to "%player%"
			if {mcusername} is "IHAH":
				set {krbad::%arg 1%} to "%arg 1%"
				message "{@c} 완료"
				stop
			else:
				message "{@c} You are don't have permission."
		set {krbad::624274923455512577} to "624274923455512577"
		set {krbad::688222392186699779} to "688222392186699779"
		set {krbad::380625576014381060} to "380625576014381060"
		set {krbad::608956812636454915} to "608956812636454915"
		set {krbad::247305812123320321} to "247305812123320321"
		set {krbad::414656853017100308} to "414656853017100308"
		set {krbad::674813875291422720} to "674813875291422720"
		set {krbad::611187913723609119} to "611187913723609119"
		set {krbad::451335803038203904} to "451335803038203904"
		message "{@c} 완료"
		stop
			
discord command 동의:
	trigger:
		if {동의::%discord id of event-user%} is false:
			set {동의::%discord id of event-user%} to true
			set {거절::%discord id of event-user%} to true
			set {reegestered::%discord id of event-user%} to true
			create embed:
				set title of the embed to "카린봇 가입"
				set the colour of the embed to GREEN
				set the description of embed to "가입이 완료되었습니다!"
				set the footer of embed to footer with text "KaRin Bot Engine by IHAH"
				reply with last created embed
		else if {servrege::%discord id of event-guild%} is true:
			set {servrege::%discord id of event-guild%} to false
			set {server::%discord id of event-guild%} to "%event-guild%`%discord id of event-guild%"
			create embed:
				set title of the embed to "서버등록 ㅡ 성공"
				set the colour of the embed to GREEN
				set the description of embed to "서버 등록이 정상적으로 등록되었습니다."
				set the footer of embed to footer with text "KaRin Bot Engine by IHAH"
				reply with last created embed
		else:
			stop
				
discord command 거절:
	trigger:
		if {거절::%discord id of event-user%} is false:
			set {거절::%discord id of event-user%} to true
			set {동의::%discord id of event-user%} to true
			create embed:
				set title of the embed to "카린봇 가입"
				set the colour of the embed to RED
				set the description of embed to "가입이 취소되었습니다."
				set the footer of embed to footer with text "KaRin Bot Engine by IHAH"
				reply with last created embed
		else if {servrege::%discord id of event-guild%} is true:
			delete {servrege::%discord id of event-guild%}
			create embed:
				set title of the embed to "서버등록 ㅡ 실패"
				set the colour of the embed to RED
				set the description of embed to "서버 등록에 실패하였습니다."
				set the footer of embed to footer with text "KaRin Bot Engine by IHAH"
				reply with last created embed
		else:
			stop
				
discord command 카린이여 [<text>] [<text>] [<text>] [<integer>]:
	trigger:
		if arg 1 is "나는":
			if arg 2 is "누구일까?":
				if {krbad::%discord id of event-user%} is set:
					reply with ":white_check_mark: | 당신은 %event-user%님 이에요! [ 봇 관리자 체크 완료됨 ]"
				else:
					if {krbpremium::%discord id of event-user%} is set:
						reply with ":white_check_mark: | 당신은 %event-user%님 이에요! [ 카린봇 프리미엄 유저 체크 완료됨 ]"
					else:
						reply with ":x: | 당신은 아무 권한도 없어요!"
				if {krbpremium::%discord id of event-guild%} is set:
					reply with "추가로 %event-guild% 서버는 카린봇 프리미엄 서버에요!"
				stop
		if {krbad::%discord id of event-user%} is "%{krbad::%discord id of event-user%}%":
			if arg 1 is "도와주거라":
				if arg 2 is not "개발자":
					create embed:
						set title of the embed to "카린봇 관리자 명령어"
						set the colour of the embed to YELLOW
						add split field named "카린이여 지정상태를" with value "[홈페이지로/도움말로/자동으로] 설정하거라" to embed
						add split field named "카린이여 공지하거라" with value "[일반/중요] [내용]" to embed
						add split field named "카린이여 경고를" with value "[추가/차감]하거라 [유저태그] [사유] (개발중)" to embed
						add split field named "카린이여 강제등록시켜라" with value "[서버ID] [전달채널ID]" to embed
						add split field named "카린이여 강제등록을취소시켜라" with value "[서버ID] [전달채널ID]" to embed
						add split field named "카린이여 관리자를" with value "설정하거라 [유저ID]" to embed
						add split field named "카린이여 검열모드를" with value "설정하거라 [서버ID]" to embed
						add split field named "카린이여 버전을" with value "설정하거라 [내용]" to embed
						add split field named "카린이여 [가입/탈퇴]시켜라" with value "[유저ID]" to embed
						add split field named "카린이여 TODO" with value "(승인/거절 TODO제목)" to embed
						add split field named "카린이여 이용제한을" with value "설정하거라 [해제: 유저아이디]" to embed
						add split field named "카린이여 이용제한을" with value "설정하거라 [설정: YYYY|MM|DD] [설정: 유저아이디]" to embed
						set the footer of embed to footer with text "KaRin Bot Engine by IHAH"
						reply with last created embed
						stop
				if arg 2 is "개발자":
					if {krbad::%discord id of event-user%} is "624274923455512577":
						create embed:
							set title of the embed to "카린봇 개발자 명령어"
							set the colour of the embed to YELLOW
							add split field named "카린이여 리로드하거라" with value "[전체/어드민/가입/습득]" to embed
							add split field named "카린이여 [종료/시작]하거라" with value "None" to embed
							add split field named "카린이여 [보아/들어/하거]라" with value "[내용]" to embed
							add split field named "카린이여 파트너서버를" with value "설정하거라 [서버ID]" to embed
							add split field named "카린이여 임시서버를" with value "[시작/종료]하거라" to embed
							add split field named "카린이여 온오프알림을" with value "설정하거라 [서버ID]" to embed
							add split field named "카린이여 시즌을" with value "설정하거라" to embed
							add split field named "카린이여 cmd" with value "[내용]" to embed
							add split field named "카린이여 [개발모드/점검모드/임시서버]를" with value "(비)활성화하거라" to embed
							set the footer of embed to footer with text "KaRin Bot Engine by IHAH"
							reply with last created embed
							stop
					else:
						add reaction "<a:no:707786855143309370>" to event-message with "{@name}"
						stop
			if arg 1 is "개발자게임을":
				if arg 2 is "설정하거라":
					set {개발자게임} to "%arg 3%"
					add reaction "<a:yes:707786803414958100>" to event-message with "{@name}"
			if arg 1 is "주식을":
				if arg 2 is "설정하거라":
					if arg 3 is set:
						if arg 4 is set:
							set {_ju} to arg 3
							set {_juu::*} to {_ju} split by "|"
							if {_juu::1} is "흐" or "흐아니" or "ㅎ" or "흐아니그래픽카드":
								if {주식::흐::%{_juu::2}%} is not set:
									set {주식::흐::%{_juu::2}%} to 0
								set {주식::흐::%{_juu::2}%} to arg 4
							if {_juu::1} is "스" or "스플" or "ㅅ" or "스플전자":
								if {주식::스::%{_juu::2}%} is not set:
									set {주식::스::%{_juu::2}%} to 0
								set {주식::스::%{_juu::2}%} to arg 4
							reply with "> 완료되었습니다.%nl%> %{_juu::2}%유저의 주식상태:%nl%> 흐아니 그래픽카드: `%{주식::흐::%{_juu::2}%}%`%nl%> 스플 전자: `%{주식::스::%{_juu::2}%}%`"
							stop
			if arg 1 is "이용제한을":
				if arg 2 is "설정하거라":
					if arg 3 is set:
						if arg 4 is set:
							if {이용제한::%arg 4%} is not set:
								set {이용제한::%arg 4%} to "%arg 4%|%arg 3%"
								add reaction "<a:yes:707786803414958100>" to event-message with "{@name}"
								stop
							else if {이용제한::%arg 4%} is set:
								reply with "<a:no:707786855143309370> %mention tag of event-user%님이 입력한 <@!%arg 4%> 유저는 이미 이용제한인 상태입니다.%nl%> 이용제한을 해제하고 싶으시다면 ``카린이여 이용제한을 설정하거라 %arg 4%`` (을)를 입력해주세요."
								stop
						else:
							if {이용제한::%arg 3%} is set:
								delete {이용제한::%arg 3%}
								add reaction "<a:yes:707786803414958100>" to event-message with "{@name}"
								stop
							else if {이용제한::%arg 3%} is set:
								reply with "<a:no:707786855143309370> %mention tag of event-user%님이 입력한 <@!%arg 4%> 유저는 이미 이용제한이 아닙니다.%nl%> 이용제한을 설정하고 싶으시다면 ``카린이여 이용제한을 설정하거라 YYYY|MM|DD %arg 4%`` (을)를 입력해주세요."
								stop
					reply with "<a:no:707786855143309370> 오류가 발생하였습니다."
					stop
			if arg 1 is "TODO":
				if {todo} is not between 0 and 20:
					set {todo} to 0
				create embed:
					set title of the embed to "TODO: %{todo}%개"
					loop {todo2::*}:
						set {_todo3::*} to loop-value split by "~!~"
						add split field named "%{_todo3::1}%" with value "%{_todo3::2}%" to embed
						add split field named " " with value " " to embed
						add split field named " " with value " " to embed
					set footer of embed to "사용자 : %event-user% | 띄어쓰기는 -(하이폰)을 사용해주세요."
					reply with last created embed
				if arg 2 is not "승인" or "거절" or "관리":
					if {krbad::%discord id of event-user%} is "624274923455512577":
						if arg 3 is set:
							if arg 3 contain "~!~":
								reply with "<a:no:707786855143309370> ``~!~``는 추가할 수 없습니다."
								stop
							else if arg 4 contain "~!~":
								reply with "<a:no:707786855143309370> ``~!~``는 추가할 수 없습니다."
								stop
							set {todosubject} to "%arg 2%"
							set {todoproject} to "%arg 3%"
							if arg 2 contain "-":
								replace all "-" in {todosubject} with " "
							if arg 3 contain "-":
								replace all "-" in {todoproject} with " "
							if {todo} is not set:
								set {todo} to 0
							add 1 to {todo}
							if {todo2::1} is not set:
								set {todo2::1} to "%{todosubject}%~!~%{todoproject}%"
							else:
								if {todo2::10} is not set:
									add "%{todosubject}%~!~%{todoproject}%" to {todo2::*}
								else:
									reply with "<a:no:707786855143309370> 현재 TODO가 10개가 되어 추가가 불가능합니다. 처리좀 빨리 하지..."
									stop
							reply with "<a:yes:707786803414958100> TODO에 [ %{todosubject}% ] 가 [ %{todoproject}% ] 로 추가되었습니다."
							stop
						else:
							if arg 2 is set:
								reply with "<a:no:707786855143309370> 제대로 된 TODO 항목을 작성해주세요."
								stop
				else:
					if arg 2 is "승인":
						if arg 3 is set:
							set {todo4} to "%arg 3%"
							if arg 3 contain "-":
								replace all "-" in {todo4} with " "
							set {count::todo} to 0
							loop {todo2::*}:
								add 1 to {count::todo}
								set {_todo3::*} to loop-value split by "~!~"
								if {_todo3::1} is {todo4}:
									reply with "<a:yes:707786803414958100> %{todo4}%가 승인되었습니다."
									delete {todo2::%{count::todo}%}
									subtract 1 from {todo}
									stop
							reply with "<a:no:707786855143309370> %{todo4}%는 없는 TODO입니다."
							stop
					if arg 2 is "거절":
						if arg 3 is set:
							set {todo4} to "%arg 3%"
							if arg 3 contain "-":
								replace all "-" in {todo4} with " "
							set {count::todo} to 0
							loop {todo2::*}:
								add 1 to {count::todo}
								set {_todo3::*} to loop-value split by "~!~"
								if {_todo3::1} is {todo4}:
									reply with "<a:yes:707786803414958100> %{todo4}%가 거절되었습니다."
									delete {todo2::%{count::todo}%}
									subtract 1 from {todo}
									stop
							reply with "<a:no:707786855143309370> %{todo4}%는 없는 TODO입니다."
							stop
					if arg 2 is "관리":
						if {krbad::%discord id of event-user%} is "624274923455512577":
							if arg 3 is "갯수":
								if arg 4 is set:
									reply with "<a:yes:707786803414958100> TODO 갯수가 %{todo}%개 에서 %arg 4%개로 변경되었습니다."
									set {todo} to arg 4
									stop
							else if arg 3 is "초기화":
								add reaction "<a:yes:707786803414958100>" to event-message with "{@name}"
								set {todo} to 0
								clear {todo2::*}
								clear {_todo3::*}
								delete {todo4}
								stop
							else:
								if {todo2::%arg 4%} is set:
									loop {todo2::*}:
										set {_todo3::*} to loop-value split by "~!~"
										if {_todo3::1} is {todo2::%arg 4%}:
											reply with "<a:yes:707786803414958100> [ %{_todo3::1}% ] TODO는 [ %{_todo3::2}% ] 내용입니다."
											stop
									reply with "<a:no:707786855143309370> 오류가 발생하였습니다."
									stop
						else:
							add reaction "<a:no:707786855143309370>" to event-message with "{@name}"
							stop
			if arg 1 is "관리자를":
				if arg 2 is "설정하거라":
					if arg 3 is set:
						if {krbad::%arg 3%} is not set:
							set {krbad::%arg 3%} to "%arg 3%"
							reply with "%mention tag of event-user% 님, <@!%arg 3%> 님이 관리자로 등록되었습니다!"
						if {krbad::%arg 3%} is set:
							delete {krbad::%arg 3%}
							reply with "%mention tag of event-user% 님, <@!%arg 3%> 님이 관리자에거 제거되었습니다!"
							stop
						else:
							reply with "<a:no:707786855143309370> 에러가 발생했습니다."
							stop
					else:
						reply with "<a:no:707786855143309370> 유저 ID를 입력해주세요!"
						stop
				else:
					reply with "> 아앗..! 명령어를 잘못 입력했어요!%nl%> ``카린이여 %arg 1% 설정하거라 [ 유저ID ]``을(를)(를) 입력해보세요!"
			if arg 1 is "임시서버를":
				if arg 2 is "시작하거라":
					reply with "임시서버가 시작되었어요!"
					set {imssi} to true
					mark event-bot with playing "임시서버가 가동중이에요!"
					stop
				if arg 2 is "종료하거라":
					reply with "임시서버가 종료되었어요!"
					mark event-bot with playing "Reloading..."
					set {imssi} to false
			if arg 1 is "온오프알림을":
				if arg 2 is "설정하거라":
					if arg 3 is set:
						if {onoffalerm::%arg 3%} is not set:
							set {onoffalerm::%arg 3%} to true
							reply with "{@b} ONOFF Alerm:%arg 3% | %{onoffalerm::%arg 3%}%"
							stop
						else if {onoffalerm::%arg 3%} is false:
							set {onoffalerm::%arg 3%} to true
							reply with "{@b} ONOFF Alerm:%arg 3% | %{onoffalerm::%arg 3%}%"
							stop
						else:
							set {onoffalerm::%arg 3%} to false
							reply with "{@b} ONOFF Alerm:%arg 3% | %{onoffalerm::%arg 3%}%"
							stop
			if arg 1 is "파트너서버를":
				if arg 2 is "설정하거라":
					if arg 3 is set:
						if {krbpremium::%arg 3%} is set:
							delete {krbpremium::%arg 3%}
							set {partner::%arg 3%} to false
							reply with "{@b} Partner:%arg 3% | %{partner::%arg 3%}%"
						else:
							set {krbpremium::%arg 3%} to "%arg 3%"
							set {partner::%arg 3%} to true
							reply with "{@b} Partner:%arg 3% | %{partner::%arg 3%}%"
							stop
			if arg 1 is "시즌을":
				if arg 2 is "설정하거라":
					if arg 3 is "MERCURY" or "VENUS" or "EARTH" or "MARS" or "JUPITER" or "SATURN" or "URANUS" or "NEPTUNE":
						delete {cmdpoint::*}
						delete {learn::*}
						delete {learner::*}
						delete {learner2::*}
						delete {kmoney::*}
						set {point::*} to 0
						set {season} to "%arg 3%"
						reply with "%mention tag of event-user%, 새로운 시즌은 ``%{season}%`` 입니다."
						stop
			if arg 1 is "호감도를":
				if arg 2 is "초기화시켜라":
					delete {point::*}
					add reaction "white_check_mark" to event-message with "{@name}"
				if arg 2 is "설정하거라":
					set {point::%arg 3%} to "%arg 4%"
					reply with "{@b} debug | %arg 3% => %{point::%arg 3%}%"
				if arg 2 is "확인하거라":
					if {point::%arg 3%} is set:
						reply with "{@b} debug | %{point::%arg 3%}%"
						stop
					else:
						reply with "{@b} Error | point is not set."
			if arg 1 is "개발모드를":
				if arg 2 is "활성화하거라":
					set {developing} to true
					reply with "{@b} debug | Developing: %{developing}%"
					if {jumgum} is true:
						set {jumgum} to false
						reply with "{@b} debug | Inspection: %{jumgum}%"
				if arg 2 is "비활성화하거라":
					set {developing} to false
					reply with "{@b} debug | Develop: %{developing}%"
			if arg 1 is "점검모드를":
				if arg 2 is "활성화하거라":
					set {jumgum} to true
					reply with "{@b} debug | Inspection: %{jumgum}%"
					if {developing} is true:
						set {developing} to false
						reply with "{@b} debug | Developing: %{developing}%"
				if arg 2 is "비활성화하거라":
					set {jumgum} to false
					reply with "{@b} debug | Inspection: %{jumgum}%"
			if arg 1 is "검열모드를":
				if arg 2 is "설정하거라":
					if {검열::%arg 3%} is not true:
						set {검열::%arg 3%} to true
						reply with "검열모드가 활성화 되었습니다."
						stop
					if {검열::%arg 3%} is true:
						set {검열::%arg 3%} to false
						reply with "검열모드가 비 활성화 되었습니다."
						stop
			if arg 1 is "버전을":
				if arg 2 is "설정하거라":
					if arg 3 is set:
						set {version} to "%arg 3%"
						reply with "버전을 %{version}% 으로 설정하였습니다."
			if arg 1 is "탈퇴시켜라":
				if {reegestered::%arg 2%} is true:
					delete {reegestered::%arg 2%}
					create embed:
						set title of the embed to "완료!"
						set the colour of the embed to GREEN
						set thumbnail of the embed to "https://cdn.discordapp.com/attachments/702363259990442048/703106691348168765/2020-04-24_7.png"
						set the description of embed to "%arg 2% 유저의 탈퇴 진행이 완료되었습니다."
						set the footer of embed to footer with text "KaRin Bot Engine by IHAH"
						reply with last created embed
						stop
			if arg 1 is "가입시켜라":
				if {reegestered::%arg 2%} is not true:
					set {reegestered::%arg 2%} to true
					create embed:
						set title of the embed to "완료!"
						set the colour of the embed to GREEN
						set thumbnail of the embed to "https://cdn.discordapp.com/attachments/702363259990442048/703106691348168765/2020-04-24_7.png"
						set the description of embed to "%arg 2% 유저의 강제 가입 진행이 완료되었습니다."
						set the footer of embed to footer with text "KaRin Bot Engine by IHAH"
						reply with last created embed
						stop
			if arg 1 is "서버등록경고를":
				if arg 2 is "설정하거라":
					if arg 4 is set:
						if arg 4 is 0 or 1 or 2 or 3 or 4 or 5 or 6 or 7 or 8 or 9 or 10 or 11 or 12 or 13 or 14 or 15 or 16 or 17 or 18 or 19 or 20:
							set {noserver::%arg 3%} to arg 4
							if arg 4 is not 20:
								if {antiserver::%arg 3%} is true:
									set {antiserver::%discord id of event-guild%} to false
							else:
								set {antiserver::%arg 3%} to true
							reply with "%arg 3% 서버는 %arg 4%회로 수정되었습니다."
							stop
						else:
							reply with "입력하신 경고 수는 0~20이 아닌 수이므로 경고 수로 수정이 불가합니다."
				if arg 2 is "확인하거라":
					if arg 3 is set:
						if {noserver::%arg 3%} is set:
							reply with "%arg 3% 서버는 %{noserver::%arg 3%}%회 입니다."
							stop
						else:
							reply with "%arg 3% 서버는 0회 입니다."
					else:
						if {noserver::%discord id of event-guild%} is set:
							reply with "현재 서버는 %{noserver::%discord id of event-guild%}%회 입니다."
						else:
							reply with "현재 서버는 0회 입니다."
				if arg 2 is "초기화시켜라":
					delete {noserver::*}
					delete {antiserver::*}
					reply with "완료"
					stop
			if arg 1 is "서버등록을":
				if arg 2 is "등록시켜라":
					if {servrege::%discord id of event-guild%} is true:
						set {servrege::%discord id of event-guild%} to false
						set {server::%discord id of event-guild%} to "%event-guild%`%arg 3%"
						create embed:
							set title of the embed to "서버등록 ㅡ 성공"
							set the colour of the embed to GREEN
							set the description of embed to "서버 등록이 정상적으로 등록되었습니다."
							set the footer of embed to footer with text "KaRin Bot Engine by IHAH"
							if arg 4 is set:
								send last created embed to channel with id "%arg 3%" with "{@name}"
							if arg 4 is not set:
								reply with last created embed
							stop
				if arg 2 is "등록해제시켜라":
					if {server::%discord id of event-guild%} is set:
						delete {server::%arg 3%}
						delete {servrege::%arg 3%}
						create embed:
							set title of the embed to "서버등록 ㅡ 취소"
							set the colour of the embed to GREEN
							set the description of embed to "서버 등록이 취소되었습니다!"
							set the footer of embed to footer with text "KaRin Bot Engine by IHAH"
							if arg 4 is set:
								send last created embed to channel with id "%arg 3%" with "{@name}"
							if arg 4 is not set:
								reply with last created embed
						stop
				if arg 2 is "확인하거라":
					reply with "카린이여 명령어에 의해 강제로 등록된 서버는 등록된 서버 이름이 남습니다!"
					reply with "서버이름 - 서버ID"
					if {server::*} is set:
						reply with "등록된 서버 목록입니다."
						loop {server::*}:
							set {_server2::*} to loop-value split by "`"
							if {_server3::1} is not set:
								reply with "등록된 서버가 없습니다!"
								if {antiserver::*} is set:
									reply with "안티서버 목록입니다."
									loop {antiserver::*}:
										set {_server3::*} to loop-value split by "`"
										if {_server3::1} is not set:
											reply with "안티서버가 없습니다!"
											stop
										reply with "``%{_server3::1}%`` - ``%{_server3::2}%``"
										delete {_server2::*}
										delete {_server3::*}
										stop
								else:
									stop
							reply with "``%{_server2::1}%`` - ``%{_server2::2}%``"
					if {antiserver::*} is set:
						reply with "안티서버 목록입니다."
						loop {antiserver::*}:
							set {_server3::*} to loop-value split by "`"
							if {_server3::1} is not set:
								reply with "안티서버가 없습니다!"
								stop
							reply with "``%{_server3::1}%`` - ``%{_server3::2}%``"
							delete {_server2::*}
							delete {_server3::*}
							stop
			if arg 1 is "지정상태를":
				if arg 2 is "홈페이지로" or "도움말로":
					if arg 3 is "설정하거라":
						reply with "{@b} %arg 2% 상태 자동 설정이 완료되었습니다."
						if arg 2 is "홈페이지로":
							mark event-bot as playing "[ http://karinbot.new.so ]"
							reply with "{@b} 현재 상태: ``[ http://karinbot.new.so ]`` Playing"
							stop
						if arg 2 is "도움말로":
							mark event-bot as playing "[ 카린아 도와줘 ] 를 입력하고 도움말을 받으세요!"
							reply with "{@b} 현재 상태: ``[ 카린아 도와줘 ] 를 입력하고 도움말을 받으세요!`` Playing"
							stop
				if arg 2 is "자동으로":
					if arg 3 is "설정하거라":
						reply with "{@b} 현재 상태: ``자동상태가 설정되었습니다.`` Playing"
						if {count::mark} is not set:
							set {count::mark} to 1
							exit
						loop {count::*}:
							set {count::mark} to 1
							mark event-bot as playing "[ http://karinbot.new.so ]"
							wait 5 seconds
							mark event-bot as playing "[ 카린아 도와줘 ] 를 입력하고 도움말을 받으세요!"
							wait 5 seconds
					if arg 3 is "설정취소하거라":
						delete {count.mark}
						reply with "{@b} 현재 상태: ``.`` Playing"
						mark event-bot as playing "."
			if arg 1 is "리로드하거라":
				if {어드민::%discord id of event-user%} is true:
					if arg 2 is "KRBEngine" or "전체":
						reply with "{@b} 카린봇 전체 서버의 리로드를 시작합니다!" and store it in {reeload}
						wait 1 second
						edit {reeload} to show "{@b} 카린봇 전체 서버를 리로드 중입니다."
						wait 1 second
						edit {reeload} to show "{@b} 카린봇 전체 서버를 리로드 중입니다.."
						wait 1 second
						edit {reeload} to show "{@b} 카린봇 전체 서버를 리로드 중입니다..."
						wait 1 second
						edit {reeload} to show "{@b} 카린봇 전체 서버의 리로드가 완료되었습니다!"
						exit
					if arg 2 is "KRBAdminEngine" or "어드민":
						reply with "{@b} 카린봇 어드민 서버의 리로드를 시작합니다!" and store it in {reeload}
						wait 1 second
						edit {reeload} to show "{@b} 카린봇 어드민 서버를 리로드 중입니다."
						wait 1 second
						edit {reeload} to show "{@b} 카린봇 어드민 서버를 리로드 중입니다.."
						wait 1 second
						edit {reeload} to show "{@b} 카린봇 어드민 서버를 리로드 중입니다..."
						wait 1 second
						edit {reeload} to show "{@b} 카린봇 어드민 서버의 리로드가 완료되었습니다!"
						exit
					if arg 2 is "KRBPlayerEngine" or "인증" or "가입":
						reply with "{@b} 카린봇 인증 & 가입 서버의 리로드를 시작합니다!" and store it in {reeload}
						wait 1 second
						edit {reeload} to show "{@b} 카린봇 인증 & 가입 서버를 리로드 중입니다."
						wait 1 second
						edit {reeload} to show "{@b} 카린봇 인증 & 가입 서버를 리로드 중입니다.."
						wait 1 second
						edit {reeload} to show "{@b} 카린봇 인증 & 가입 서버를 리로드 중입니다..."
						wait 1 second
						edit {reeload} to show "{@b} 카린봇 인증 & 가입 서버의 리로드가 완료되었습니다!"
						exit
					if arg 2 is "KRBsdEngine" or "습득":
						reply with "{@b} 카린봇 습득 서버의 리로드를 시작합니다!" and store it in {reeload}
						wait 1 second
						edit {reeload} to show "{@b} 카린봇 습득 서버를 리로드 중입니다."
						wait 1 second
						edit {reeload} to show "{@b} 카린봇 습득 서버를 리로드 중입니다.."
						wait 1 second
						edit {reeload} to show "{@b} 카린봇 습득 서버를 리로드 중입니다..."
						wait 1 second
						edit {reeload} to show "{@b} 카린봇 습득 서버의 리로드가 완료되었습니다!"
						exit
					delete {reeload}
				else:
					reply with "{@b} 당신은 권한이 없습니다!"
			if arg 1 is "종료하거라":
				if {어드민::%discord id of event-user%} is true:
					set {krbon} to false
					reply with "[ ! ] GoodBye!"
					stop
				else:
					reply with "{@b} 당신은 권한이 없습니다!"
			if arg 1 is "시작하거라":
				if {어드민::%discord id of event-user%} is true:
					set {krbon} to true
					reply with "[ ! ] Hello!"
					stop
				else:
					reply with "{@b} 당신은 권한이 없습니다!"
			if arg 1 is "보아라" or "들어라" or "하거라":
				if {adminlogined::%discord id of event-user%} is "Admin":
					if arg 1 is "보아라":
						mark event-bot as watching "%arg 2% %arg 3%"
						reply with "{@b} 현재 상태: ``%arg 2% %arg 3%`` Watching"
					if arg 1 is "하거라":
						mark event-bot as playing "%arg 2% %arg 3%"
						reply with "{@b} 현재 상태: ``%arg 2% %arg 3%`` Playing"
					if arg 1 is "들어라":
						mark event-bot as listening to "%arg 2% %arg 3%"
						reply with "{@b} 현재 상태: ``%arg 2% %arg 3%`` Listening"
				else:
					add reaction "no_entry" to event-message with "{@name}"
			if arg 1 is "경고를":
				if arg 4 is set:
					if arg 2 is "추가하거라":
						add 1 to {krbwarn::%{_warner}%}
						create embed:
							set title of the embed to "경고 부여"
							set the colour of the embed to RED
							set the description of embed to "%mention tag of event-user% -> <@!%arg 4%> %nl%%nl%사유: %arg 4%%nl%현재 경고: %{krbwarn::%arg 3%}%"
							set the footer of embed to footer with text "KaRin Bot Engine by IHAH"
							reply with last created embed
					if arg 2 is "차감하거라":
						remove 1 from {krbwarn::%{_warner}%}
						create embed:
							set title of the embed to "경고 차감"
							set the colour of the embed to GREEN
							set the description of embed to "%mention tag of event-user% -> <@!%arg 4%> %nl%%nl%사유: %arg 4%%nl%현재 경고: %{krbwarn::%arg 3%}%"
							set the footer of embed to footer with text "KaRin Bot Engine by IHAH"
							reply with last created embed
			if arg 1 is "공지하거라":
				if arg 3 is set:
					if arg 2 is not "일반" or "중요":
						reply with "> 아앗..! 명령어를 잘못 입력했어요!%nl%> ``카린이여 %arg 1% [ 일반 / 중요 ] [ 내용 ]``을(를)(를) 입력해보세요!"
						stop
					else:
						set {공지} to "%arg 3%"
						set {공지확인} to "%arg 2%"
						set {annchannels} to 0
						loop {cid::*}:
							add 1 to {annchannels}
						create embed:
							set title of the embed to "%{annchannels}%개의 채널(서버)에 공지를 보냅니다."
							set the colour of the embed to GREEN
							add split field named "공지의 내용은 다음과 같습니다." with value "%arg 3%" to embed
							set the footer of embed to footer with text "[확인]을 입력하여 공지를 보내고 [취소]를 입력하여 공지를 취소합니다."
							reply with last created embed and store it in {공지텍스트}
				else:
					reply with "> 아앗..! 명령어를 잘못 입력했어요!%nl%> ``카린이여 %arg 1% [ 일반 / 중요 ] [ 내용 ]``을(를)(를) 입력해보세요!"
			if arg 1 is not set:
				reply with "> 아앗..! 명령어를 잘못 입력했어요!%nl%> ``카린이여 도와주거라``을(를)(를) 입력해보세요!"
		else:
			add reaction "no_entry" to event-message with "{@name}"

on track end seen by "{@name}":
	remove "%{nowmusic::1}%DCISGREAT%{nowmusic::2}%" from {trr::*}
	if {trr::*} is set:
		loop {trr::*}:
			add 1 to {count}
			set {ttrr::*} to loop-value split at "DCISGREAT"
			stop the track event-bot is playing
			search youtube for {ttrr::1} and store the results in {rresults::*}
			play {rresults::1}
			set {nowmusic::1} to {ttrr::1}
			set {nowmusic::2} to {ttrr::2}
			delete {count}
			delete {ttrr::*}
			delete {rresults::*}
			stop
	else:
		make event-bot leave vc
		delete {count}
		delete {ttrr::*}
		delete {rresults::*}
		delete {nowmusic::*}

discord command +m.pause:
	trigger:
		if {krbad::%discord id of event-user%} is "624274923455512577":
			pause the track event-bot is playing
			reply with ":pause_button: Paused!"
		else:
			create embed:
				set title of the embed to "Error:"
				set the colour of the embed to RED
				set the description of embed to "You do not have permission!"
				set the footer of embed to footer with text "KaRin Bot Engine by IHAH"
				reply with last created embed

discord command +m.resume:
	trigger:
		if {krbad::%discord id of event-user%} is "624274923455512577":
			resume the track event-bot is playing
			reply with ":arrow_forward: Resumed!"
		else:
			create embed:
				set title of the embed to "Error:"
				set the colour of the embed to RED
				set the description of embed to "You do not have permission!"
				set the footer of embed to footer with text "KaRin Bot Engine by IHAH"
				reply with last created embed

discord command +m.info:
	trigger:
		if event-bot is playing:
			make embed:
				set title of embed to title with text ":arrow_forward: %discord name of track event-bot is playing%" and link "%url of track event-bot is playing%"
				set the colour of the embed to Cyan
				add field named "Time remaining" with value "%difference between position of track event-bot is playing and duration of track event-bot is playing%" to embed
				add field named "Author" with value "%authors of track event-bot is playing%" to embed
		else:
			make embed:
				set title of embed to title with text ":stop_button: No track playing"
				reply with last created embed
				
discord command _cm [<integer>] [<text>]:
	trigger:
		if {krbad::%discord id of event-user%} is "624274923455512577" or "688222392186699779":
			if arg 1 is set:
				if arg 2 is set:
					delete event-message with event-bot
					send "%arg 2%" to channel with id "%arg 1%" with "{@name}"
				else:
					create embed:
						set title of the embed to "Error:"
						set the colour of the embed to RED
						set the description of embed to "message is not set"
						set the footer of embed to footer with text "KaRin Bot Engine by IHAH"
						reply with last created embed
			else:
				create embed:
					set title of the embed to "Error:"
					set the colour of the embed to RED
					set the description of embed to "channel id is not set"
					set the footer of embed to footer with text "KaRin Bot Engine by IHAH"
					reply with last created embed
		else:
			create embed:
				set title of the embed to "Error:"
				set the colour of the embed to RED
				set the description of embed to "You do not have permission."
				set the footer of embed to footer with text "KaRin Bot Engine by IHAH"
				reply with last created embed

discord command _dm [<integer>] [<text>]:
	trigger:
		if {krbad::%discord id of event-user%} is "624274923455512577":
			if arg 1 is set:
				if arg 2 is set:
					delete event-message with event-bot
					send "%arg 2%" to user with id "%arg 1%" with "{@name}"
				else:
					create embed:
						set title of the embed to "Error:"
						set the colour of the embed to RED
						set the description of embed to "message is not set"
						set the footer of embed to footer with text "KaRin Bot Engine by IHAH"
						reply with last created embed
			else:
				create embed:
					set title of the embed to "Error:"
					set the colour of the embed to RED
					set the description of embed to "user id is not set"
					set the footer of embed to footer with text "KaRin Bot Engine by IHAH"
					reply with last created embed
		else:
			create embed:
				set title of the embed to "Error:"
				set the colour of the embed to RED
				set the description of embed to "You do not have permission."
				set the footer of embed to footer with text "KaRin Bot Engine by IHAH"
				reply with last created embed

discord command 카린아 [<text>] [<text>] [<text>]:
	trigger:
		if {jumgum} is true:
			if {krbad::%discord id of event-user%} is not "624274923455512577":
				stop
		else:
			if {이용제한::%discord id of event-user%} is set:
				stop
			if arg 1 is "가입":
				if {reegestered::%discord id of event-user%} is not set:
					set {동의::%discord id of event-user%} to false
					set {거절::%discord id of event-user%} to false
					create embed:
						set title of the embed to "카린봇 가입"
						set the colour of the embed to RED
						set the description of embed to "카린봇에 가입을 하면 아래의 [개인정보수집약관](http://gg.gg/KRBginf)과 [이용약관](http://gg.gg/KRBiinf2)에 동의하는 것으로 간주합니다.%nl%%nl%약관에 동의하시고 가입을 진행하시려면 ``동의``을(를), 약관에 동의하지 않으면 ``거절`` 을 입력해주세요."
						set the footer of embed to footer with text "KaRin Bot Engine by IHAH"
						reply with last created embed
						wait 10 seconds
						if {동의::%discord id of event-user%} is false:
							reply with "%mention tag of event-user%, 서버 등록이 취소되었습니다."
							delete {동의::%discord id of event-user%}
							delete {거절::%discord id of event-user%}
						stop
				else:
					reply with "이미 가입되었습니다!"
			if {server::%discord id of event-guild%} is set:
				if arg 1 is "따라해":
					if {reegestered::%discord id of event-user%} is true:
						if arg 2 is set:
							add 1 to {count::%discord id of event-user%}
							create an invite to event-channel
							send "%last created invite%%nl%``%{_amount::3}%``을(를) 해당 서버에서 따라했습니다.%nl%저장된 칸: %discord id of event-user%-%{count::%discord id of event-user%}%" to channel with id "{@log}" with "{@name}"
							if {reeplysys::%discord id of event-user%::%{count::%discord id of event-user%}%} is set:
								reply with "이미 등록된 칸입니다. 따라하기가 취소됩니다."
								stop
							else:
								delete event-message with event-bot
								if arg 3 is set:
									reply with "%arg-2% %arg-3%" and store it in {reeplysys::%discord id of event-user%::%{count::%discord id of event-user%}%}
								else:
									reply with "%arg-2%" and store it in {reeplysys::%discord id of event-user%::%{count::%discord id of event-user%}%}
						else:
							add reaction "x"" to event-message with "{@name}"
					else:
						reply with "카린아 가입 또는 카린아 regester로 가입해보세요!"
						stop
				if arg 1 is "초대링크":
					reply with "현재 이 시스템은 점검중입니다."
					stop
					create an invite to event-channel
					reply with "%last created invite%"
					reply with "**24시간동안만 지속됩니다. 24시간이 지나면 다시 명령어를 입력해서 초대링크를 새로 만들어주세요.**"
				if arg 1 is "문의":
					if arg 2 is set:
						add 1 to {mcount}
						delete event-message with event-bot
						create embed:
							set title of the embed to "완료!"
							set the colour of the embed to BLUE
							set the description of embed to "문의 내용이 전달되었습니다."
							set the footer of embed to footer with text "KaRin Bot Engine by IHAH"
							reply with last created embed
						if {kr} is not 1:
							set {kr} to 1
							set {dcount::%{mcount}%} to "%{mcount}%"
							create embed:
								set title of the embed to "%{mcount}%번째 문의 :: %event-user% [ %discord id of event-user% ]"
								set the colour of the embed to BLUE
								if arg 3 is not set:
									set the description of embed to "%arg-2%"
								else:
									set the description of embed to "%arg-2% %arg-3%"
								set the footer of embed to footer with text "KaRin Bot Engine by IHAH"
								send last created embed to channel with id "{@log}" with "{@name}"
								wait 2 ticks
								delete {kr}
							if {kr1} is not 1:
								set {kr1} to 1
								create embed:
									set title of the embed to "완료!"
									set the colour of the embed to BLUE
									set the description of embed to "문의 내용이 전달되었습니다."
									set the footer of embed to footer with text "KaRin Bot Engine by IHAH"
									reply with last created embed
									wait 2 ticks
									delete {kr}
					else:
						create embed:
							set title of the embed to "문의 주의사항"
							set the colour of the embed to ORANGE
							set the description of embed to "1. 자잘한 문의만 문의 시스템으로 해주세요. (카린아 문의 [문의사항])%nl%2. 문의를 보내고 24시간이 넘은 경우 카카오톡ID sweetdw08로 친구추가 후 카톡을 보내주세요.%nl%3. 만약 카카오톡도 답장이 없다면 Dm을 남겨주세요.%nl%4. 1번에 맞지 않는 건의 또는 문의 등은 https://github.com/KaRinKaRin876/KRB-v2/issues (으)로 새 이슈를 만들어 주세요."
							set the footer of embed to footer with text "KaRin Bot Engine by IHAH"
							reply with last created embed
							stop
				if arg 1 is "후원":
					if arg 2 is not set:
						create embed:
							set title of the embed to "후원 안내"
							set the colour of the embed to RED
							set the description of embed to "카린봇 후원은 ``카린아 후원 [컬처랜드 핀코드]`` 형태로 작성해주세요.%nl%계좌는 받지 않고 있습니다."
							set the footer of embed to footer with text "KaRin Bot Engine by IHAH"
							send last created embed to user with id "%discord id of event-user%" with "{@name}"
					if arg 2 is set:
						delete event-message with event-bot
						if {kr} is not 1:
							set {kr} to 1
							create embed:
								set title of the embed to "%event-user% [ %discord id of event-user% ] 님의 후원입니다."
								set the colour of the embed to BLUE
								set the description of embed to "%arg 1%"
								set the footer of embed to footer with text "KaRin Bot Engine by IHAH"
								send last created embed to channel with id "{@log}" with "{@name}"
								wait 2 ticks
								delete {kr}
							if {kr1} is not 1:
								set {kr1} to 1
								create embed:
									set title of the embed to "후원 안내"
									set the colour of the embed to BLUE
									set the description of embed to "후원처리가 정상적으로 완료되었습니다.%nl%24시간 내에 확인 처리 됩니다.%nl%%nl%컬처랜드 핀코드: %arg 1%"
									set the footer of embed to footer with text "KaRin Bot Engine by IHAH"
									send last created embed to user with id "%discord id of event-user%" with "{@name}"
									wait 2 ticks
									delete {kr}
				if arg 1 is "업로드":
					if arg 2 contain "http":
						delete event-message with event-bot
						upload "%arg 2%" to event-channel
						stop
					if arg 2 is "링피트":
						upload "https://cdn.discordapp.com/attachments/706152196944953486/707932453452513380/unknown.png" to event-channel
						stop
					if arg 2 is "원더vs애플":
						upload "https://cdn.discordapp.com/attachments/706152196944953486/707947864310939720/unknown.png" to event-channel
						stop
					if arg 2 is "유니티":
						upload "https://cdn.discordapp.com/attachments/706152196944953486/708292058011664404/20200505_224413.gif" to event-channel
						stop
					if arg 2 is "만렙후라이팬":
						upload "https://cdn.discordapp.com/attachments/373085162411393037/711547096561614858/3d13893d6dde0d53.gif" to event-channel
						stop
					else:
						create embed:
							set title of the embed to "Error:"
							set the colour of the embed to RED
							set the description of embed to "링크를 첨부해주세요."
							set the footer of embed to footer with text "KaRin Bot Engine by IHAH"
							reply with last created embed
				if arg 1 is "뮤직":
					if arg 2 is "도움말":
						add reaction "regional_indicator_d" to event-message with "{@name}"
						wait 0.5 seconds
						add reaction "regional_indicator_m" to event-message with "{@name}"
						wait 0.5 seconds
						create embed:
							set title of the embed to "카린봇 뮤직 명령어"
							set the colour of the embed to YELLOW
							set the description of embed to "카린아 뮤직 재생 [유튜브 영상 제목] - [유튜브 영상 제목]에 적은 제목을 유튜브에서 검색합니다.%nl%+m.s - 지금 재생중인 음악을 스킵합니다.%nl%카린아 뮤직 볼륨 - 봇의 볼륨을 설정합니다."
							set the footer of embed to footer with text "KaRin Bot Engine by IHAH"
							send last created embed to user with id "%discord id of event-user%" with "{@name}"
					if arg 2 is "들어와" or "컴온":
						if voice channel of event-member is set:
							set {joinvc} to true
							join voice channel of event-member
							add reaction "white_check_mark" to event-message with "{@name}"
						else:
							add reaction "x" to event-message with "{@name}"
					if arg 2 is "스킵" or "넘겨":
						if {krbad::%discord id of event-user%} is "624274923455512577":
							stop the track event-bot is playing
							add reaction "white_check_mark" to event-message with "{@name}"
						else:
							create embed:
								set title of the embed to "Error:"
								set the colour of the embed to RED
								set the description of embed to "You do not have permission!"
								set the footer of embed to footer with text "KaRin Bot Engine by IHAH"
								reply with last created embed
					if arg 2 is "나가" or "꺼져":
						if {joinvc} is true:
							if {krbad::%discord id of event-user%} is "624274923455512577":
								set {joinvc} to false
								stop the track event-bot is playing
								make event-bot leave vc
								add reaction "white_check_mark" to event-message with "{@name}"
							else:
								create embed:
									set title of the embed to "Error:"
									set the colour of the embed to RED
									set the description of embed to "You do not have permission!"
									set the footer of embed to footer with text "KaRin Bot Engine by IHAH"
									reply with last created embed
						else:
							add reaction "x" to event-message with "{@name}"
					if arg 2 is "재생" or "플레이":
						delete event-message with event-bot
						if voice channel of event-member is not set:
							reply with "<a:no:707786855143309370> 고객님은 통화방에 들어가 있으셔야 해요!"
							stop
						if arg 3 is set:
							search youtube for arg-3 and store the results in {ree::*}
							if {ree::1} is not set:
								reply with "<a:no:707786855143309370> %arg-3%를 검색하였으나, 아무 결과가 나오지 않았습니다 :("
								stop
							if {trr::*} is not set:
								join voice channel of event-member
								set {joinvc} to true
								wait 1.5 seconds
								play {ree::1}
								reply with "%{ree::1}%를 재생합니다."
								set {nowmusic::1} to {ree::1}
								set {nowmusic::2} to arg-3
								add "%{ree::1}%DCISGREAT%arg-3%" to {trr::*}
								create embed:
									set the title of embed to title with text "현재 음악 목록"
									set the colour of the embed to ORANGE
									loop {trr::*}:
										add 1 to {count.music}
										set {ttrr::*} to {trr::%{count}%} split at "DCISGREAT"
										add split field named "%{count.music}%" with value "**[ %{ttrr::2}% ]**%nl%``%{ttrr::1}%``" to embed
										add split field named " " with value " " to embed
										add split field named " " with value " " to embed
									send "콘솔" to console
									delete {ttrr::*}
									delete {count}
									reply with last created embed
							else:
								add "%{ree::1}%DCISGREAT%arg-3%" to {trr::*}
								create embed:
								set the title of embed to title with text "현재 음악 목록"
								set the colour of the embed to ORANGE
								loop {trr::*}:
									add 1 to {count.music}
									set {ttrr::*} to {trr::%{count.music}%} split at "DCISGREAT"
									add split field named "%{count.music}%" with value "**[ %{ttrr::2}% ]**%nl%``%{ttrr::1}%``" to embed
									add split field named " " with value " " to embed
									add split field named " " with value " " to embed
									send "d%{count}%" to console
									send {ttrr::2} to console
								reply with last created embed
								delete {count}
								delete {ttrr::*}
					if arg 2 is "볼륨":
						if {dc} is not set:
							set {dc} to "true"
							if arg-3 parsed as int is not integer:
								create embed:
									set title of the embed to "뮤직 ㅡ 볼륨"
									set the colour of the embed to YELLOW
									set the description of embed to "%volume of event-bot%"
									set the footer of embed to footer with text "KaRin Bot Engine by IHAH"
									reply with last created embed
								wait 1 tick
								delete {dc}
								stop
							if arg-3 is set:
								if {krbpremium::%discord id of event-user%} is true:
									set {nowvol} to "%volume of event-bot%"
									set the volume of event-bot to arg-3 parsed as int
									create embed:
										set title of the embed to "뮤직 ㅡ 볼륨 ( 설정됨 )"
										set the colour of the embed to YELLOW
										set the description of embed to "%{nowvol}% -> %volume of event-bot%"
										set the footer of embed to footer with text "KaRin Bot Engine by IHAH"
										reply with last created embed
									wait 1 tick
									delete {dc}
									stop
								else:
									create embed:
										set title of the embed to "뮤직 ㅡ 볼륨"
										set the colour of the embed to YELLOW
										set the description of embed to "%volume of event-bot%"
										set the footer of embed to footer with text "KaRin Bot Engine by IHAH"
										reply with last created embed
									wait 1 tick
									delete {dc}
									stop
			else:
				add 1 to {noserver::%discord id of event-guild%}
				
discord command _logout:
	trigger:
		if {krbad::%discord id of event-user%} is "624274923455512577":
			delete {krbad::%discord id of event-user%}
			reply with "{@b} GoodBye! See you later!"
			stop
			
discord command 카린앙 [<text>] [<text>] [<text>] [<text>] [<text>]:
	trigger:
		if {jumgum} is true:
			if {krbad::%discord id of event-user%} is not "624274923455512577":
				create embed:
					set title of the embed to "점검중!"
					set the colour of the embed to CYAN
					set the description of embed to "현재는 카린봇 점검모드 입니다!%nl%점검모드엔 관리자를 제외한 유저들이 명령어를 사용할 수 없습니다!"
					set the footer of embed to footer with text "KaRin Bot Reply Engine by IHAH"
					reply with last created embed
					stop
		else:
			if arg 1 is "임베드따라해":
				if {reegestered::%discord id of event-user%} is true:
					if arg 2 is not set:
						create embed:
							set title of the embed to "Error:"
							set the colour of the embed to RED
							set the description of embed to "[ 카린아 임베드따라해 제목 색깔 내용 추가내용  ] 형식으로 입력해주세요.%nl%임베드따라해는 - 로 띄어쓰기가 가능하며, 내용 한정으로 (줄바꿈) 으로 줄바꿈이 가능합니다."
							set the footer of embed to footer with text "KaRin Bot Reply Engine by IHAH"
							reply with last created embed
					if arg 2 is set:
						create embed:
							if arg 2 is not "없음":
								set {_embed::title} to "%arg 2%"
								if arg 2 contain "-":
									replace all "-" in {_embed::title} with " "
								set title of the embed to "%{_embed::title}%"
							if arg 3 is not "없음":
								set the colour of the embed to arg 3 parsed as color
							if arg 4 is set:
								set {_embed::descrip} to "%arg 4%"
								if arg 4 contain "-":
									replace all "-" in {_embed::descrip} with " "
								if arg 4 contain "(줄바꿈)":
									replace all "(줄바꿈)" in {_embed::descrip} with "%nl%"
								set the description of embed to "%{_embed::descrip}%"
							if arg 5 is set:
								set {_embed::footer} to "%arg 5%"
								if arg 5 contain "-":
									replace all "-" in {_embed::footer} with " "
								set the footer of embed to footer with text "%{_embed::footer}%"
							reply with last created embed
				else:
					reply with "+가입 또는 +regester 를 입력하여 카린봇에 가입해보세요!"

discord command 카주식 [<text>] [<text>] [<integer>]:
	trigger:
		if arg 1 is "지갑":
			reply with "흐아니 그래픽카드: `%{주식::흐::%discord id of event-user%}%`주%nl%스플 전자: `%{주식::스::%discord id of event-user%}%`주"
			set {흐} to 100
			set {스} to 10
		if arg 1 is "매수":
			if arg 2 is not set:
				reply with "> 아앗..! 명령어를 잘못 입력했어요!%nl%> ``카주식 매수 [회사명] [갯수]`` (을)를 입력해 주세요."
			else:
				if arg 2 is "흐" or "흐아니" or "ㅎ" or "흐아니그래픽카드":
					#if arg 3 is "올인" or "모두":
					#	if {kmoney::%discord id of event-user%} >= {흐}:
					#		if {주식::흐::%discord id of event-user%} is not set:
					#			set {주식::흐::%discord id of event-user%} to 0
					#		add {kmoney::%discord id of event-user%}/{흐} to {주식::흐::%discord id of event-user%}
					#		set {남은돈::%discord id of event-user%} to {kmoney::%discord id of event-user%}
					#		set {주식구매::%discord id of event-user%} to {_amount::5} parsed as int
					if arg 3 is between 1 and 500:
						if {kmoney::%discord id of event-user%} >= {흐}*arg 3:
							if {주식::흐::%discord id of event-user%} is not set:
								set {주식::흐::%discord id of event-user%} to 0
							set {유저} to {흐}*arg 3
							add {kmoney::%discord id of event-user%}/{유저} to {주식::흐::%discord id of event-user%}
							set {남은돈::%discord id of event-user%} to {kmoney::%discord id of event-user%}-{흐}*arg 3
							set {주식구매::%discord id of event-user%} to arg 3
						else:
							reply with "당신은 그만큼 돈이 없는 것 같은데요?"
							stop
					else:
						reply with "주식을 1개보다 작거나 500개보다 크게 구매할 수 없어요!"
						stop
					reply with "`흐아니그래픽카드` 회사의 주식을 `%{주식구매::%discord id of event-user%}%`주 구매하였습니다. 남은 돈: `%{남은돈::%discord id of event-user%}%`K"
				if arg 2 is "스" or "스플" or "ㅅ" or "스플전자":
					#if {_amount::5} is "올인" or "모두":
					#	if {kmoney::%discord id of event-user%} >= {스}:
					#		if {주식::스::%discord id of event-user%} is not set:
					#			set {주식::스::%discord id of event-user%} to 0
					#		add {kmoney::%discord id of event-user%}/{스} to {주식::스::%discord id of event-user%}
					#		set {남은돈::%discord id of event-user%} to {kmoney::%discord id of event-user%}
					#		set {주식구매::%discord id of event-user%} to {_amount::5} parsed as int
					if arg 3 is between 1 and 500:
						if {kmoney::%discord id of event-user%} >= {스}*arg 3:
							if {주식::스::%discord id of event-user%} is not set:
								set {주식::스::%discord id of event-user%} to 0
							set {유저} to {스}*arg 3
							add {kmoney::%discord id of event-user%}/{유저} to {주식::스::%discord id of event-user%}
							set {남은돈::%discord id of event-user%} to {kmoney::%discord id of event-user%}-{스}*arg 3
							set {주식구매::%discord id of event-user%} to arg 3
						else:
							reply with "당신은 그만큼 돈이 없는 것 같은데요?"
							stop
					else:
						reply with "주식을 1개보다 작거나 500개보다 크게 구매할 수 없어요!"
						stop
					reply with "`스플전자` 회사의 주식을 `%{주식구매::%discord id of event-user%}%`주 구매하였습니다. 남은 돈: `%{남은돈::%discord id of event-user%}%`K"

on reaction added:
	if event-emote is white_check_mark:
		reply with "%mention tag of event-user%, 완료된 명령어 입니다."
		remove event-emote added by event-user from event-message
	if event-emote is x:
		reply with "%mention tag of event-user%, 정확한 실행이 되지 않았거나 오류가 발생했습니다."
		remove event-emote added by event-user from event-message
	if event-emote is no_entry:
		reply with "%mention tag of event-user%, ``7 (Bot Dev)`` 권한이 필요합니다."
		remove event-emote added by event-user from event-message

On guild message received seen by "{@name}":
	if {logsugipserver::%discord id of event-guild%} is true:
		send "[채팅데이터] %discord id of event-user%/%event-user%/%discord id of event-guild%/%event-guild%/%discord id of event-channel%/%event-channel% : %event-string%" to channel with id "%{logchannel::%discord id of event-guild%}%" with "{@name}"
		if {logsugip::%discord id of event-guild%} is true:
			send "[채팅데이터] %discord id of event-user%/%event-user%/%discord id of event-guild%/%event-guild%/%discord id of event-channel%/%event-channel% : %event-string%" to console
	if event-string is "확인" or "취소":
		if {공지} is set:
			if event-string is "확인":
				if {공지확인} is "일반":
					create embed:
						set title of the embed to "카린봇 ㅡ 일반공지"
						set the colour of the embed to GREEN
						set the description of embed to "%{공지}%%nl%%nl%:link: [카린봇 추천하러 가기](https://koreanbots.dev/bots/%discord id of event-bot%)%nl%:link: [카린봇 지원 디스코드 입장하기](https://discord.gg/sZ7E5Kt)%nl%:link: [카린봇 홈페이지 바로가기](http://karinbot.new.so)%nl%:link: [팀 리에토 디스코드 입장하기](https://discord.gg/55n4jnm)%nl%:link: [카린봇 이용약관 확인하기](http://gg.gg/KRBiinf2)%nl%%nl%항상 이용해주셔서 감사합니다."
						set the footer of embed to footer with text "사용자: %event-user% - 인증됨 | %now%"
				if {공지확인} is "중요":
					create embed:
						set title of the embed to "카린봇 ㅡ 중요공지"
						set the colour of the embed to ORANGE
						set the description of embed to "%{공지}%%nl%%nl%:link: [카린봇 추천하러 가기](https://koreanbots.dev/bots/%discord id of event-bot%)%nl%:link: [카린봇 지원 디스코드 입장하기](https://discord.gg/sZ7E5Kt)%nl%:link: [카린봇 홈페이지 바로가기](http://karinbot.new.so)%nl%:link: [팀 리에토 디스코드 입장하기](https://discord.gg/55n4jnm)%nl%:link: [카린봇 이용약관 확인하기](http://gg.gg/KRBiinf2)%nl%%nl%항상 이용해주셔서 감사합니다."
						set the footer of embed to footer with text "사용자: %event-user% - 인증됨 | %now%"
				loop {cid::*}:
					set {announce} to loop-value
					send last created embed to channel with id "%{announce}%" with "{@name}"
					if {anncid} is not set:
						set {anncid} to "%{announce}%"
					else:
						set {anncid} to "%{anncid}%%nl%%{announce}%"
				create embed:
					set the colour of the embed to GREEN
					set the description of embed to "현재 추가된 모든 채널에 공지가 전송되었습니다.%nl%%{anncid}%"
					edit {공지텍스트} to show last created embed
			else:
				create embed:
					set the colour of the embed to GREEN
					set the description of embed to "공지 보내기가 취소되었습니다."
					edit {공지텍스트} to show last created embed
			delete {공지}
			delete {공지확인}
			delete {anncid}
			delete {공지텍스트}
			stop
		else:
			stop
	if {learndeleteing::%discord id of event-user%} is true:
		if event-string is not "카린아 잊히기 고정 종료":
			if {learn::%event-string%} is set:
				send "[습득명령어 삭제시도] %discord id of event-user%/%event-user%/%discord id of event-guild%/%event-guild%/%discord id of event-channel%/%event-channel% : %event-string%" to console
				if {krbad::%discord id of event-user%} is set:
					loop {learn::*}:
						set {_amount2::*} to loop-value split by "~!~"
						if {_amount2::2} contain "(줄바꿈)":
							replace all "(줄바꿈)" in {_amount2::2} with "%nl%"
						if {dc} is not true:
							set {dc} to true
							send "[습득명령어 삭제성공] %discord id of event-user%/%event-user%/%discord id of event-guild%/%event-guild%/%discord id of event-channel%/%event-channel% : %event-string%" to console
							reply with "```%{_amount2::2}%```%nl%``%{_amount2::3}%``님이 알려준 명령어에요!"
							delete {learn::%event-string%}
							wait 2 tick
							delete {dc}
							stop
				else:
					if {learner2::%event-string%} is "%discord id of event-user%":
						loop {learn::*}:
							set {_amount2::*} to loop-value split by "~!~"
							if {_amount2::2} contain "(줄바꿈)":
								replace all "(줄바꿈)" in {_amount2::2} with "%nl%"
							if {dc} is not true:
								set {dc} to true
								send "[습득명령어 삭제성공] %discord id of event-user%/%event-user%/%discord id of event-guild%/%event-guild%/%discord id of event-channel%/%event-channel% : %event-string%" to console
								reply with "```%{_amount2::2}%```%nl%``%{_amount2::3}%``님이 알려준 명령어에요!"
								delete {learn::%event-string%}
								wait 2 tick
								delete {dc}
								stop
					else:
						send "[습득명령어 삭제실패] %discord id of event-user%/%event-user%/%discord id of event-guild%/%event-guild%/%discord id of event-channel%/%event-channel% : %event-string%" to console
						stop
	if event-string contain "^^ㅣ" or "샹" or "썅" or "ㅄ" or "ㅂㅅ" or "병신" or "씨발" or "애미" or "간나" or "좆" or "보지" or "자지" or "섹스" or "ㅆㅂ" or "ㅅㅂ" or "ㅄ" or "시발" or "새끼" or "느금마" or "ㄴㄱㅁ" or "야동" or "떽뜨" or "^^ㅣ발" or "ㅆㅂ" or "온더비치" or "온더 비치" or "nigger" or "bitch" or "sex" or "엄준식" or "ㄴㅇㅁ" or "ㅇㅁ" or "발레" or "자위" or "신음" or "지랄" or "ㅈㄹ" or "ㅇㅎㅎ" or "에헤헤" or "tq" or "tlqkf" or "ㅅㅂ" or "시발" or "씨발" or "Tlqkf" or "ㅅㅅ" or "섹스" or "꼰대" or "꼬라지" or "개떡같은" or "개같은" or "지랄" or "새끼" or "시발" or "퍽큐" or "인간말종" or "인간쓰레기" or "똥꼬" or "똥방구" or "또라이" or "자위행위" or "성행위" or "ㅗ":
		if {검열::%discord id of event-guild%} is true:
			delete event-message with event-bot
			reply with "%mention tag of event-user%, 어허! 그런말 하면 안댕"
			stop
	else if event-string contain "카린이여":
		loop {cid2::*}:
			set {karinieu} to loop-value
			send "[관리자 명령어 데이터] %discord id of event-user%/%event-user%/%discord id of event-guild%/%event-guild%/%discord id of event-channel%/%event-channel% : %event-string%" to channel with id "%{karinieu}%" with "{@name}"
		send "[관리자 명령어 데이터] %discord id of event-user%/%event-user%/%discord id of event-guild%/%event-guild%/%discord id of event-channel%/%event-channel% : %event-string%" to console
		set {_} to event-string
		set {_amount::*} to {_} split by " "
		if {_amount::1} is "카린이여":
			if {_amount::2} is "대화추가":
				if {krbad::%discord id of event-user%} is "%discord id of event-user%":
					if {_amount::3} is "돈" or "정보" or "내정보" or "호감도" or "서버등록해제" or "시간" or "서버등록" or "ㄷㅇㅈ" or "도와줘" or "도움말" or "문의" or "따라해" or "습득" or "ㅅㄷ" or "나루토" or "ㄴㄾ" or "ㄴㄹㅌ" or "ㄷㅇㅁ" or "뮤직" or "초대코드" or "초대링크" or "잊어" or "습득제거" or "ㅅㄷㅈㄱ" or "습득모두제거" or "ㅅㄷㅁㄷㅈㄱ" or "습득확인" or "ㅅㄷㅎㅇ" or "카린유튜브" or "명언" or "임베드따라해" or "업로드" or "후원" or "유저정보" or "가입" or "도와주거라" or "탈퇴시켜라" or "가입시켜라" or "지정상태를" or "리로드하거라" or "종료하거라" or "시작하거라" or "보아라" or "들어라" or "하거라" or "경고를" or "공지하거라":
						reply with "<a:no:707786855143309370> %mention tag of event-user%님, 그 명령어는 카린봇 기존 명령어라서 등록이 불가능해요!"
						stop
					else:
						if {daehwa::%{_amount::3}%} is not set:
							if {_amount::3} contain "-":
								replace all "-" in {_amount::3} with " "
							if {_amount::4} contain "-":
								replace all "-" in {_amount::4} with " "
							set {daehwalearner2::%{_amount::3}%} to "%discord id of event-user%"
							set {daehwa::%{_amount::3}%} to "%{_amount::3}%~!~%{_amount::4}%~!~%{learner::%{_amount::3}%}%"
							reply with "<a:yes:707786803414958100> %mention tag of event-user%님! ``%{_amount::3}%``가 ``%{_amount::4}%``군요! 이제 알겠어요!"
							send "습득됨 [ ``%{_amount::3}%`` - ``%{_amount::4}%`` ] By ``%event-user%(%discord id of event-user%``" to channel with id "{@log}" with "{@name}"
							send "[습득된 명령어] %discord id of event-user%/%event-user%/%discord id of event-guild%/%event-guild%/%discord id of event-channel%/%event-channel% : %{_amount::3}% - %{amount::4}%"
						else:
							if {_amount::4} contain "-":
								replace all "-" in {_amount::4} with " "
							reply with "``%{_amount::3}%``은 이미 알고있어요! 하지만 ``%{_amount::4}%``도 좋은것 같네요!"
			stop
	else if event-string contain "카린아" or "%{접두사::%discord id of event-guild%}% " or "%{접두사::%discord id of event-guild%}%" or "카린아?":	
		set {광고} to random integer between 1 and 10
		if {광고} is 10:
			create embed:
				set title of the embed to "[광고] 개발자에게 도움을!"
				set the colour of the embed to BLUE
				set the description of embed to "개발자에게 도움을 주는 :heart:를 %nl%[여기](https://koreanbots.dev/bots/685715386745880581)에서 눌러주세요!%nl%:heart:는 개발자에게 큰 도움이 됩니다!"
				set the footer of embed to footer with text "KaRin Bot Engine By IHAH"
				reply with last created embed
		set {user::%discord id of event-user%} to "%event-user%"
		if event-user is bot:
			stop
		if {user::%discord id of event-user%} contain "봇" or "Bot" or "BOT":
			stop
		send "[명령어데이터] %discord id of event-user%/%event-user%/%discord id of event-guild%/%event-guild%/%discord id of event-channel%/%event-channel% : %event-string%" to console
		if event-string is "카린아 서버상태":
			create embed:
				set the colour of the embed to CYAN
				if {jumgum} is true:
					set title of the embed to "점검중!"
					set the description of embed to "현재는 카린봇 점검모드 입니다!%nl%점검모드엔 관리자를 제외한 유저들이 명령어를 사용할 수 없습니다!"
				else if {developing} is true:
					set title of the embed to "개발중!"
					set the description of embed to "현재는 카린봇 개발모드 입니다!%nl%명령어 사용이 가능합니다."
				else if {imssi} is true:
					set title of the embed to "임시서버 가동중!"
					set the description of embed to "현재는 카린봇 임시서버 모드 입니다!%nl%임시서버 전용 명령어 사용만 가능합니다."
				else:
					set title of the embed to "정상 작동 중!"
					set the description of embed to "현재는 정상 작동 중 입니다!%nl%명령어 사용이 가능합니다."
				set the footer of embed to footer with text "KaRin Bot Reply Engine by IHAH"
				reply with last created embed
				stop
		else:
			if {jumgum} is true:
				if {krbad::%discord id of event-user%} is not "624274923455512577":
					create embed:
						set title of the embed to "점검중!"
						set the colour of the embed to CYAN
						set the description of embed to "현재는 카린봇 점검모드 입니다!%nl%점검모드엔 관리자를 제외한 유저들이 명령어를 사용할 수 없습니다!"
						set the footer of embed to footer with text "KaRin Bot Reply Engine by IHAH"
						reply with last created embed
						stop
				exit
			if {이용제한::%discord id of event-user%} is set:
				set {이용제한이라고::*} to {이용제한::%discord id of event-user%} split by "|"
				reply with "<a:no:707786855143309370> 당신은 현재 이용제한 조치 되었습니다."
				if {이용제한이라고::2} is "9999":
					if {이용제한이라고::3} is "99":
						if {이용제한이라고::4} is "99":
							reply with "```이용 제한 해제 날짜: ~Infinity```"
						else:
							reply with "```이용 제한 해제 날짜: ~%{이용제한이라고::2}%년 %{이용제한이라고::3}%월 %{이용제한이라고::4}%일```"
					else:
						reply with "```이용 제한 해제 날짜: ~%{이용제한이라고::2}%년 %{이용제한이라고::3}%월 %{이용제한이라고::4}%일```"
				else:
					reply with "```이용 제한 해제 날짜: ~%{이용제한이라고::2}%년 %{이용제한이라고::3}%월 %{이용제한이라고::4}%일```"
				stop
			set {_} to event-string
			set {_amount::*} to {_} split by " "
			if {_amount::1} is not "카린아" or "카린이여":
				stop
			if {_amount::2} is "서버등록":
				if {server::%discord id of event-guild%} is not set:
					if {antiserver::%discord id of event-guild%} is not true:
						set {servrege::%discord id of event-guild%} to true
						create embed:
							set title of the embed to "카린봇 ㅡ 서버 등록"
							set the colour of the embed to YELLOW
							set thumbnail of the embed to "https://cdn.discordapp.com/attachments/702363259990442048/703106691348168765/2020-04-24_7.png"
							set the description of embed to "카린봇의 서버 진행을 등록하시면 [개인정보 수집 약관](http://gg.gg/KRBginf)과 [카린봇 이용 약관](http://gg.gg/KRBiinf2)에 동의하는 것으로 간주합니다.%nl%%nl%약관에 동의하시고 등록을 진행하시려면 10초 내에 ``동의``을(를),%nl%등록을 취소하려면 ``거절`` 을 입력하시거나 10초를 기다려 주세요."
							set the footer of embed to footer with text "KaRin Bot Engine by IHAH"
							reply with last created embed
						wait 10 seconds
						if {servrege::%discord id of event-guild%} is true:
							reply with "%mention tag of event-user%, 서버 등록이 취소되었습니다."
							delete {servrege::%discord id of event-guild%}
						stop
					else:
						reply with "서버 등록을 하지 않고 명령어를 %{noserver::%discord id of event-guild%}%회 사용하셨습니다."
						reply with "서버 등록을 하지 않고 명령어를 20회 이상 사용하셨기 때문에 서버 등록이 불가능하게 되었습니다."
						reply with "이 메세지가 보이면 봇 관리자를 불러 서버 등록 불가 상황을 해제시켜 주세요."
						stop
				else:
					reply with "이미 등록되었습니다!"
			if {server::%discord id of event-guild%} is set:
				if {_amount::1} is "카린아?":
					set {karina} to random integer between 1 and 3
					if {karina} is 1:
						reply with "뭐"
					else if {karina} is 2:
						reply with "ㅇㅉ"
					else if {karina} is 3:
						reply with "?"
					if {cmdpoint::%{_amount::2}%::%discord id of event-user%} is not set:
						set {cmdpoint::%{_amount::2}%::%discord id of event-user%} to true
						set {pointa} to random integer between 1 and 5
						reply with "``P +%{pointa}% 획득!``"
						if {point::%discord id of event-user%} is not set:
							set {point::%discord id of event-user%} to {pointa}
							stop
						else:
							add {pointa} to {point::%discord id of event-user%}
							stop
				if {_amount::2} is "나루토" or "ㄴㄹㅌ" or "ㄴㄾ":
					if {naruto} is not set:
						reply with "미\안\하\다 이\거 보\여\주\려\고 어\그\로\끌\었\다.. 나\루\토 사\스\케 싸움수준 ㄹㅇ실화냐? 진짜 세계관최강자들의 싸움이다.. 그찐따같던 나\루\토가 맞나? 진짜 나\루\토는 전설이다..진짜옛날에 맨날나\루\토봘는데 왕같은존재인 호카게 되서 세계최강 전설적인 영웅이된나\루\토보면 진짜내가다 감격스럽고 나\루\토 노래부터 명장면까지 가슴울리는장면들이 뇌리에 스치면서 가슴이 웅장해진다.. 그리고 극장판 에 카카시앞에 운석날라오는 거대한 걸 사스케가 갑자기 순식간에 나타나서 부숴버리곤 개간지나게 나\루\토가 없다면 마을을 지킬 자는 나밖에 없다 라며 바람처럼 사라진장면은 진짜 나\루\토처음부터 본사람이면 안울수가없더라 진짜 너무 감격스럽고 보루토를 최근에 알았는데 미안하다.. 지금20화보는데 진짜 나\루\토세대나와서 너무 감격스럽고 모두어엿하게 큰거보니 내가 다 뭔가 알수없는 추억이라해야되나 그런감정이 이상하게 얽혀있다.. 시노는 말이많아진거같다 좋은선생이고..그리고 보루토왜욕하냐 귀여운데 나\루\토를보는것같다 성격도 닮았어 그리고버루토에 나\루\토사스케 둘이싸워도 이기는 신같은존재 나온다는게 사실임?? 그리고인터닛에 쳐봣는디 이거 ㄹㅇㄹㅇ 진짜팩트냐?? 저적이 보루토에 나오는 신급괴물임?ㅡ 나\루\토사스케 합체한거봐라 진짜 ㅆㅂ 이거보고 개충격먹어가지고 와 소리 저절로 나오더라 ;; 진짜 저건 개오지는데.. 저게 ㄹㅇ이면 진짜 꼭봐야돼 진짜 세계도 파괴시키는거아니야 .. 와 진짜 나\루\토사스케가 저렇게 되다니 진짜 눈물나려고했다.. 버루토그라서 계속보는중인데 저거 ㄹㅇ이냐..? 하.. ㅆㅂ 사스케 보고싶다..  진짜언제 이렇게 신급 최강들이 되었을까 옛날생각나고 나 중딩때생각나고 뭔가 슬프기도하고 좋기도하고 감격도하고 여러가지감정이 복잡하네.. 아무튼 나\루\토는 진짜 애니중최거명작임.." and store it in {naruto}
						if {cmdpoint::%{_amount::2}%::%discord id of event-user%} is not set:
							set {cmdpoint::%{_amount::2}%::%discord id of event-user%} to true
							set {pointa} to random integer between 1 and 5
							reply with "``P +%{pointa}% 획득!``"
							if {point::%discord id of event-user%} is not set:
								set {point::%discord id of event-user%} to {pointa}
							else:
								add {pointa} to {point::%discord id of event-user%}
						wait 10 seconds
						edit {naruto} to show "***(갸우뚱?)***"
						delete {naruto}
					else:
						reply with "너무 빨라요!"
				else if {_amount::2} is "토큰":
					if {token} is not set:
						reply with "Njg1NzE1Mzg2NzQ1ODgwNTgx.XqKhdA.2shS6PNHy-qA1cG_bQADa0niB2A" and store it in {token}
						wait 0.1 second
						edit {token} to show "***(갸우뚱?)***"
						delete {token}
						stop
					else:
						reply with "너무 빨라요!"
						stop
				else if {_amount::2} is "카린":
					reply with "이세상에서 가장 귀엽고 잘생긴 사람이다!"
					if {cmdpoint::%{_amount::2}%::%discord id of event-user%} is not set:
						set {cmdpoint::%{_amount::2}%::%discord id of event-user%} to true
						set {pointa} to random integer between 1 and 5
						reply with "``P +%{pointa}% 획득!``"
						if {point::%discord id of event-user%} is not set:
							set {point::%discord id of event-user%} to {pointa}
							stop
						else:
							add {pointa} to {point::%discord id of event-user%}
							stop
				else if {_amount::2} is "넌":
					if {_amount::3} is "누구니?":
						reply with "카린봇 이에요!"
						if {cmdpoint::%{_amount::2}%::%discord id of event-user%} is not set:
							set {cmdpoint::%{_amount::2}%::%discord id of event-user%} to true
							set {pointa} to random integer between 1 and 5
							reply with "``P +%{pointa}% 획득!``"
							if {point::%discord id of event-user%} is not set:
								set {point::%discord id of event-user%} to {pointa}
								stop
							else:
								add {pointa} to {point::%discord id of event-user%}
								stop
				else if {_amount::2} is "hellothisisverification":
					reply with "! 6개장4발면 8701 ( 624274923455512577 )"
					reply with "샵을 표시 못해서 (주석 처리됨) 일단 이대로 표시해둡니다."
					stop
				else if {_amount::2} is "핑":
					reply with "안대~! 내 핑은 못본단 말이양~!"
					if {cmdpoint::%{_amount::2}%::%discord id of event-user%} is not set:
						set {cmdpoint::%{_amount::2}%::%discord id of event-user%} to true
						set {pointa} to random integer between 1 and 5
						reply with "``P +%{pointa}% 획득!``"
						if {point::%discord id of event-user%} is not set:
							set {point::%discord id of event-user%} to {pointa}
							stop
						else:
							add {pointa} to {point::%discord id of event-user%}
							stop
				else if {_amount::2} contain "도와줘" or "도움말" or "ㄷㅇㅈ" or "ㄷㅇㅁ":
					if {_amount::3} is "기본" or "ㄱㅂ" or "습득" or "ㅅㄷ" or "rlqhs" or "rq" or "tmqemr" or "te" or "ajsl" or "ehs" or "money":
						reply with "mention tag of event-user%"
					if {_amount::3} is not "기본" or "ㄱㅂ" or "습득" or "ㅅㄷ":
						#add reaction "regional_indicator_d" to event-message with "{@name}"
						#wait 0.5 seconds
						#add reaction "regional_indicator_m" to event-message with "{@name}"
						#wait 0.5 seconds
						create embed:
							set title of the embed to "카린봇 도움말 목록"
							set the colour of the embed to YELLOW
							set {ttrr::*} to {trr::%{count}%} split at "DCISGREAT"
							add split field named "카린아 뮤직 도움말" with value "카린봇 뮤직 시스템의 도움말을 살펴봐요!" to embed
							add split field named "카린아 도와줘 기본" with value "카린봇 기본 시스템의 도움말을 살펴봐요!" to embed
							add split field named "카린아 도와줘 습득" with value "카린봇 습득 시스템의 도움말을 살펴봐요!" to embed
							add split field named "카린아 도와줘 머니" with value "카린봇 머니 시스템의 도움말을 살펴봐요!" to embed
							add split field named "ㅋ도와줘" with value "카린봇 뮤직 서버의 도움말을 살펴봐요!" to embed
							set the footer of embed to footer with text "KaRin Bot Engine by IHAH"
							if {jumgum} is not true:
								reply with last created embed
								#send last created embed to user with id "%discord id of event-user%" with "{@name}"
					if {_amount::3} is "기본" or "ㄱㅂ" or "rlqhs" or "rq":
						if {_amount::4} is not "2" or "3":
							#add reaction "regional_indicator_d" to event-message with "{@name}"
							#wait 0.5 seconds
							#add reaction "regional_indicator_m" to event-message with "{@name}"
							#wait 0.5 seconds
							create embed:
								set title of the embed to "카린봇 메인 명령어"
								set the colour of the embed to YELLOW
								add split field named "카린아 초대링크" with value "해당 채널의 초대링크를 생성합니다!" to embed
								add split field named "카린아 따라해" with value "[텍스트] - [텍스트] 를 따라합니다." to embed
								add split field named "카린아 카린유튜브" with value "카린이의 유튜브 링크를 확인합니다." to embed
								add split field named "카린아 문의" with value "[문의내용] - [문의내용] 을 카린에게 전달합니다." to embed
								add split field named "카린아 후원" with value "카린봇 후원 도움말입니다." to embed
								add split field named "카린앙 임베드따라해" with value "임베드 형식으로 따라합니다." to embed
								add split field named "카린아 따라해수정" with value "카린아 따라해 로 따라한 말을 수정합니다. (개발중)" to embed
								add split field named "카린아 업로드" with value "[링크] - 입력한 명령어를 삭제하고 [링크]를 첨부합니다." to embed
								add split field named "카린아 초대코드" with value "카린봇을 초대할 수 있는 링크를 받습니다." to embed
								set the footer of embed to footer with text "카린아 도움말 기본 [페이지] 로 도움말 페이지를 확인해주세요! | 페이지 : 1 / 3"
								if {jumgum} is not true:
									reply with last created embed
						if {_amount::4} is "2":
							create embed:
								set title of the embed to "카린봇 메인 명령어"
								set the colour of the embed to YELLOW
								add split field named "카린아 멘션" with value "[유저ID] - 카린봇이 대신 멘션해줍니다." to embed
								add split field named "카린아 투표" with value "[시작/제거] - 투표를 합니다. (개발중)" to embed
								add split field named "카린아 접두사" with value "[접두사] - 접두사를 설정합니다. (개발중)" to embed
								add split field named "카린아 시간계산" with value "[초] - 시간을 시, 분, 초 단위로 계산합니다. (개발중)" to embed
								add split field named "카린아 계산" with value "(개발중)" to embed
								add split field named "카린아 깃헙" with value "카린봇 깃헙으로 갈 수 있는 링크를 받습니다." to embed
								add split field named "카린아 홈페이지" with value "리에토 홈페이지로 갈 수 있는 링크를 받습니다." to embed
								add split field named "카린아 버전" with value "카린아 따라해 로 따라한 말을 수정합니다. (개발중)" to embed
								add split field named "카린아 내정보" with value "카린봇 내 자신의 정보를 확인합니다." to embed
								set the footer of embed to footer with text "카린아 도움말 기본 [페이지] 로 도움말 페이지를 확인해주세요! | 페이지 : 2 / 3"
								if {jumgum} is not true:
									reply with last created embed
						if {_amount::4} is "3":
							create embed:
								set title of the embed to "카린봇 메인 명령어"
								set the colour of the embed to YELLOW
								add split field named "카린아 정보" with value "카린봇의 정보를 확인합니다." to embed
								add split field named "카린아 호감도" with value "나의 카린봇과의 호감도를 확인합니다." to embed
								add split field named "카린아 시간" with value "현재 시간을 확인합니다." to embed
								add split field named "카린아 명언" with value "[1~6] - 명언을 확인합니다." to embed
								set the footer of embed to footer with text "카린아 도움말 기본 [페이지] 로 도움말 페이지를 확인해주세요! | 페이지 : 3 / 3"
								if {jumgum} is not true:
									reply with last created embed
					if {_amount::3} is "습득" or "ㅅㄷ" or "tmqemr" or "te":
						#add reaction "regional_indicator_d" to event-message with "{@name}"
						#wait 0.5 seconds
						#add reaction "regional_indicator_m" to event-message with "{@name}"
						#wait 0.5 seconds
						create embed:
							set title of the embed to "카린봇 습득 명령어"
							set the colour of the embed to YELLOW
							add split field named "카린아 습득" with value "카린아 습득 [명령어] [할말]%nl%카린아 [명령어] 입력시 [할말]을 나타냅니다!" to embed
							add split field named "카린아 [명령어]" with value "카린아 습득 명령어로 습득한 말을 나타냅니다!" to embed
							set the footer of embed to footer with text "KaRin Bot Engine by IHAH"
							if {jumgum} is not true:
								reply with last created embed
								#send last created embed to user with id "%discord id of event-user%" with "{@name}"
					if {_amount::3} is "돈" or "머니" or "ehs" or "ajsl" or "money":
						#add reaction "regional_indicator_d" to event-message with "{@name}"
						#wait 0.5 seconds
						#add reaction "regional_indicator_m" to event-message with "{@name}"
						#wait 0.5 seconds
						create embed:
							set title of the embed to "카린봇 메인 명령어"
							set the colour of the embed to YELLOW
							add split field named "카린아 돈 지갑" with value "자신의 지갑을 봅니다!" to embed
							add split field named "카린아 돈 받기" with value "잔액이 없을경우 특정 이벤트로 돈을 받습니다." to embed
							add split field named "카린아 돈 배팅" with value "잔액의 전체를 가지고 배팅합니다." to embed
							add split field named "카린아 돈 선물" with value "자신이 원하는 금액의 돈을 선물해요." to embed
							add split field named "카린아 돈 통장" with value "자신의 통장에 접근합니다!" to embed
							set the footer of embed to footer with text "KaRin Bot Money Engine by IHAH"
							if {jumgum} is not true:
								reply with last created embed
								#send last created embed to user with id "%discord id of event-user%" with "{@name}"
				else if {_amount::2} is "밴목록" or "밴" or "언밴" or "추방":
					if {_amount::2} is "밴목록":
						grab bans of event-guild
						reply with "밴 목록: `%grabbed bans%`"
					else if {_amount::2} is "밴":
						if arg-3 is set:
							ban {_amount::3} from guild with id "%discord id of event-guild%" due to "%{_amount::4}%" as "봇이름"
							reply with "%{_amount::3}%를 밴했습니다!"
					else if {_amount::2} is "언밴":
						if {_amount::3} is set:
							unban {_amount::3} from event-guild
							reply with "%{_amount::3}%를 언밴했습니다!"
					else if {_amount::2} is "추방":
						if arg-3 is set:
							kick {_amount::3} from guild with id "%discord id of event-guild%" due to "%{_amount::4}%" as "봇이름"
							reply with "%{_amount::3}%를 추방했습니다!"
					stop
				else if {_amount::2} is "호출":
					reply with "봇 관리자 호출이 완료되었습니다."
					loop {krbad::*}:
						send "<@%loop-value%>님, %mention tag of event-user%님이 호출했습니다! %mention tag of event-channel%" to user with id "%loop-value%" with "{@name}"
				else if {_amount::2} is "내아이디":
					reply with "%mention tag of event-user%, 당신의 디스코드 아이디는 %discord id of event-user%입니다."
				else if {_amount::2} is "멘션":
					set {_amount::3} to {_amount::3} parsed as int
					if {_amount::3} is between 0 and 999999999999999999:
						reply with "<a:yes:707786803414958100> %mention tag of event-user%님이 <@!%{_amount::3}%>님을 멘션하셨습니다."
				else if {_amount::2} is "채팅로그설정":
					if {_amount::3} is set:
						if {_amount::3} is "0":
							if {_amount::4} is "콘솔로그제거":
								set {logsugip::%discord id of event-user%} to false
							set {logsugipserver::%discord id of event-guild%} to false
							delete {logchannel::%discord id of event-guild%}
							reply with "<a:yes:707786803414958100> ``%event-guild%``의 채팅 로그 채널이 삭제되었습니다."
							stop
						set {logsugip::%discord id of event-user%} to true
						set {logsugipserver::%discord id of event-guild%} to true
						set {logchannel::%discord id of event-guild%} to "%{_amount::3}%"
						reply with "<a:yes:707786803414958100> ``%{_amount::3}%`` 채널이 ``%event-guild%``의 채팅 로그 채널로 등록되었습니다."
				else if {_amount::2} is "관리자로그설정":
					if {_amount::3} is set:
						if {_amount::3} is "0":
							delete {cid2::%discord id of event-guild%}
							reply with "<a:yes:707786803414958100> ``%event-guild%``의 카린봇 관리자 명령어 로그 채널이 삭제되었습니다."
							stop
						set {cid2::%discord id of event-guild%} to {_amount::3} parsed as int
						reply with "<a:yes:707786803414958100> ``%{_amount::3}%`` 채널이 ``%event-guild%``의 카린봇 관리자 명령어 로그 채널로 등록되었습니다."
				else if {_amount::2} is "공지채널설정":
					if {_amount::3} is set:
						if {_amount::3} is "0":
							set {cid::%discord id of event-guild%} to {_amount::3} parsed as int
							reply with "<a:yes:707786803414958100> ``%event-guild%``의 카린봇 공지사항 채널이 삭제되었습니다."
							stop
						set {cid::%discord id of event-guild%} to {_amount::3} parsed as int
						reply with "<a:yes:707786803414958100> ``%{_amount::3}%`` 채널이 ``%event-guild%``의 카린봇 공지사항 채널로 등록되었습니다."
				else if {_amount::2} is "돈":
					if {_amount::3} is "받기":
						if {kmoney::%discord id of event-user%} is set:
							if {kmoney::%discord id of event-user%} is 0:
								reply with "당신은 `돈`을 잡았다! ``+ 1000K``"
								set {kmoney::%discord id of event-user%} to 1000
								stop
							else:
								reply with "죄송해요.. %mention tag of event-user%님은 잔액이 있어서 돈을 지급할 수가 없어요.."
								stop
						else:
							reply with "당신은 지갑이 없는 것 같아요..%nl%``카린아 돈 지갑``을(를) 통해 지갑을 발급하세요!"
					if {_amount::3} is "지갑":
						if {_amount::4} is set:
							if {kmoney::%{_amount::4}%} is set:
								replace all "<@!" in {_amount::4} with ""
								replace all ">" in {_amount::4} with ""
								reply with "제가 조회해본 결과, <@!%{_amount::4}%>님은 지갑에 ``%{kmoney::%{_amount::4}%}%``원을 보유하고 있어요!"
								#if {kcard::%{_amount::4}%} is set:
								#	reply with "추가로 <@!%{_amount::4}%>님은 통장에 ``%{kcard::%discord id of event-user%}%``원을 보유하고 있어요!"
								#else:
								#	reply with "추가로 <@!%{_amount::4}%>님은 통장을 보유하고 있지 않아요!"
							else:
								reply with "제가 조회해본 결과, <@!%{_amount::4}%>님은 지갑이 존재하지 않아요!"
						else:
							if {kmoney::%discord id of event-user%} is set:
								reply with "제가 조회해본 결과, %mention tag of event-user%님은 지갑에 ``%{kmoney::%discord id of event-user%}%``원을 보유하고 있어요!"
								#if {kcard::%discord id of event-user%} is set:
								#	reply with "추가로 %mention tag of event-user%님은 통장에 ``%{kcard::%discord id of event-user%}%``원을 보유하고 있어요!"
								#else:
								#	reply with "추가로 %mention tag of event-user%님은 통장을 보유하고 있지 않아요!"
							else:
								reply with "제가 조회해본 결과, %mention tag of event-user%님은 지갑이 없어서, 지갑을 발급 해드렸어요!%nl%신규 발급 기념으로 ``10000``원을 지급 해드렸어요!"
								set {kmoney::%discord id of event-user%} to 10000
					if {kmoney::%discord id of event-user%} is set:
						if {_amount::3} is "배팅":
							if {_amount::4} is "일반":
								set {baeting} to random integer between 1 and 4
								if {baeting} is 1:
									if {_amount::5} is not set:
										reply with "> 아앗..! 당신은 돈을 잃어버렸어요!%nl%``카린아 돈 받기`` 명령어를 사용해 보세요!"
										set {kmoney::%discord id of event-user%} to 0
									else:
										reply with "> 아앗..! 당신은 돈을 잃어버렸어요!%nl%현재 잔액: ``%{kmoney::%discord id of event-user%}-{_amount::5}%``원"
										remove {_amount::5} from {kmoney::%discord id of event-user%}
									stop
								if {baeting} is 2 or 3:
									if {_amount::5} is not set:
										reply with "우아! 당신은 돈을 지켜냈어요!%nl%``%{kmoney::%discord id of event-user%}%``K를 되돌려 받았어요!"
									else:
										reply with "우아! 당신은 돈을 지켜냈어요!%nl%``%{_amount::5}%``K를 되돌려 받았어요!"
									stop
								if {baeting} is 4:
									if {_amount::5} is set:
										add {_amount::5} to {kmoney::%discord id of event-user%}
										reply with "우아! 당신은 돈을 따냈어요!%nl%``%{_amount::5}%``K를 획득했어요!"
									else:
										add {kmoney::%discord id of event-user%} to {kmoney::%discord id of event-user%}
										reply with "우아! 당신은 돈을 따냈어요!%nl%``%{kmoney::%discord id of event-user%}%``K를 획득했어요!"
									stop
								else:
									reply with "에러가 발생한 것 같아요!%nl%``%{kmoney::%discord id of event-user%}%``K를 돌려드렸어요!"
							if {_amount::4} is "가위바위보":
								if {_amount::5} is "가위" or "바위" or "보":
									set {gawibawibo} to random integer between 1 and 3
									if {gawibawibo} is 1:
										if {_amount::5} is "가위":
											reply with "%mention tag of event-user%: :v: vs :v: :%mention tag of event-bot% => 비겼습니다. ``%{kmoney::%discord id of event-user}%``K를 되돌려 받았어요!"
										else if {_amount::5} is "바위":
											reply with "%mention tag of event-user%: :fist: vs :v: :%mention tag of event-bot% => 당신이 이겼습니다.  ``%{kmoney::%discord id of event-user}%``K를 획득했어요!"
										else:
											reply with "%mention tag of event-user%: :raised_back_of_hand: vs :v: :%mention tag of event-bot% => 제가 이겼습니다.  ``%{kmoney::%discord id of event-user}%``K를 잃어버렸어요!"
									else if {gawibawibo} is 2:
										if {_amount::5} is "바위":
											reply with "%mention tag of event-user%: :fist: vs :fist: :%mention tag of event-bot% => 비겼습니다. ``%{kmoney::%discord id of event-user}%``K를 되돌려 받았어요!"
										else if {_amount::5} is "가위":
											reply with "%mention tag of event-user%: :raised_back_of_hand: vs :fist: :%mention tag of event-bot% => 당신이 이겼습니다.  ``%{kmoney::%discord id of event-user}%``K를 획득했어요!"
										else:
											reply with "%mention tag of event-user%: :v: vs :fist: :%mention tag of event-bot% => 제가 이겼습니다.  ``%{kmoney::%discord id of event-user}%``K를 잃어버렸어요!"
									else:
										if {_amount::5} is "보":
											reply with "%mention tag of event-user%: :raised_back_of_hand: vs :raised_back_of_hand: :%mention tag of event-bot% => 비겼습니다. ``%{kmoney::%discord id of event-user%}%``K를 되돌려 받았어요!"
										else if {_amount::5} is "가위":
											reply with "%mention tag of event-user%: :v: vs :raised_back_of_hand: :%mention tag of event-bot% => 당신이 이겼습니다.  ``%{kmoney::%discord id of event-user}%``K를 획득했어요!"
										else:
											reply with "%mention tag of event-user%: :fist: vs :raised_back_of_hand: :%mention tag of event-bot% => 제가 이겼습니다.  ``%{kmoney::%discord id of event-user}%``K를 잃어버렸어요!"
							else:
								reply with "> 아앗..! 명령어를 잘못 입력했어요!%nl%> ``%{_amount::1}% %{_amount::2}% %{_amount::3}% 일반`` 또는 > ``%{_amount::1}% %{_amount::2}% %{_amount::3}% 가위바위보 가위/바위/보`` 을 입력해보세요!"
						if {_amount::3} is "내놔":
							if {krbad::%discord id of event-user%} is "624274923455512577":
								if {_amount::4} is set:
									if {_amount::4} contain "." or "`" or "~" or "!" or "@" or "$" or "^" or "&" or "*" or "(" or ")" or "_" or "+" or "=" or "[" or "]" or "{" or "}" or ";" or ":" or "/" or ">" or "<" or "," or "?":
										reply with "%mention tag of event-user%님, 특수부호는 허락되지 않습니다."
									else:
										set {kmoney::%discord id of event-user%} to {kmoney::%discord id of event-user%}+{_amount::4}
										reply with "네, %mention tag of event-user%님에게 %{_amount::4}%K를 지급했어요! 잔액: %{kmoney::%discord id of event-user%}%"
								else:
									reply with "> 아앗..! 명령어를 잘못 입력했어요!%nl%> ``%{_amount::1}% %{_amount::2}% %{_amount::3}% [금액]``을(를) 입력해보세요!"
							else:
								add reaction "no_entry" to event-message with "{@name}"
						else:
							if {_amount::3} is not "도움말" or "받기" or "지갑":
								add reaction "x" to event-message with "{@name}"
								reply with "> 아앗..! 제가 찾을 수 있는 명령어가 없어요!%nl%``카린아 돈 도움말`` 명령어를 사용해보세요!"	
						if {_amount::3} is "통장":
							reply with "개발중인 명령어에요!"
							stop
					#		if {_amount::4} is "입금":
					#			if {kcard::%discord id of event-user%} is set:
					#				if {_amount::5} is set:
					#					if {kmoney::%discord id of event-user%} >= {_amount::4}:
					#						add {_amount::5} to {kcard::%discord id of event-user%}
					#						subtract {_amount::5} from {kmoney::%discord id of event-user%}
					#						reply with "당신은 ``%{_amount::5}%``K를 통장에 입금했어요!%nl%현재 잔액:%nl%돈: ``%{kmoney::%discord id of event-user%}%``K%nl%통장: ``%{kcard::%discord id of event-user%}%``K"
					#					else:
					#						reply with "당신의 잔액이 통장에 넣고 싶은 금액보다 적어요!"
					#			else:
					#				reply with "당신은 통장이 없어요! 때문에 당신의 통장을 발급해드렸어요!"
					#				set {kcard::%discord id of event-user%} to 0
					#		if {_amount::4} is "출금":
					#			if {kcard::%discord id of event-user%} is set:
					#				if {_amount::5} is set:
					#					if {kcard::%discord id of event-user%} >= {_amount::4}:
					#						add {_amount::5} to {kmoney::%discord id of event-user%}
					#						subtract {_amount::5} from {kcard::%discord id of event-user%}
					#						reply with "당신은 ``%{_amount::5}%``K를 통장에서 출금했어요!%nl%현재 잔액:%nl%돈: ``%{kmoney::%discord id of event-user%}%``K%nl%통장: ``%{kcard::%discord id of event-user%}%``K"
					#					else:
					#						reply with "당신이 K하는 금액보다 통장의 잔액이 적어요!"
					#		else if {_amount::4} is not "입금" or "출금":
					#			reply with "> 아앗..! 명령어를 잘못 입력했어요!%nl%> ``%{_amount::1}% %{_amount::2}% %{_amount::3}% 입금`` 또는 > ``%{_amount::1}% %{_amount::2}% %{_amount::3}% 출금`` 을 입력해보세요!"
					#	if {_amount::3} is "선물":
					#		if {_amount::4} is set:
					#			if {_amount::5} is set:
					#				if {kmoney::%{_amount::4}%} is set:
					#					if {_amount::5} contain "-" or "Infinity" or "infinity":
					#							reply with "%mention tag of event-user%님, - 또는 Infinity는 사용하실 수 없습니다."
					#					else:
					#						if {kmoney::%discord id of event-user%} >= {_amount::5}:
					#							remove {_amount::5} from {kmoney::%discord id of event-user%}
					#							add {_amount::5} to {kmoney::%{_amount::4}%}
					#							reply with "%mention tag of event-user%님, <@!%{_amount::4}%> 님에게 ``%{_amount::5}%``K의 선물이 완료되었어요!"
					#						else:
					#							reply with "%mention tag of event-user%님, 당신은 그만큼 충분히 돈이 있지 않아요!"
					#				else:
					#					reply with "%mention tag of event-user%님, 해당 유저( <@!%{_amount::4}%> )는 돈 시스템에 가입되어 있지 않아요!"
					#			else:
					#				reply with "> 아앗..! 명령어를 잘못 입력했어요!%nl%> ``%{_amount::1}% %{_amount::2}% %{_amount::3}% %{_amount::4}% [금액]`` 을 입력해보세요!"
					#		else:
					#			reply with "> 아앗..! 명령어를 잘못 입력했어요!%nl%> ``%{_amount::1}% %{_amount::2}% %{_amount::3}% [유저ID] [금액]`` 을 입력해보세요!"
					#else:
					#	reply with "> 아앗..! 당신은 지갑을 발급하지 않았어요..!"
				else if {_amount::2} contain "투표":
					if {_amount::3} contain "시작":
						if {toophyo::%discord id of event-user%} is not set:
							if {_amount::8} is not set:
								reply with "> 아앗..! 명령어를 잘못 입력했어요!%nl%> ``%{_amount::1}% %{_amount::2}% %{_amount::3}% [투표제목] [단일내용1] [이모지1 (: 없이)] [단일내용2] [이모지2 (: 없이)]``을(를) 입력해보세요!"
							else:
								if {_amount::6} contain ":":
									reply with ":를 이모지에 추가시킬 수 없어요! :를 빼고 입력해주세요!"
									stop
								else if {_amount::8} contain ":":
									reply with ":를 이모지에 추가시킬 수 없어요! :를 빼고 입력해주세요!"
									stop
								else:
									reply with "투표 개설을 위해 잠시만 기다려주세요!" and it in store {toophyo::%discord id of event-user%}
									create embed:
										set title of the embed to "투표 - %{_amount::4}%"
										set the colour of the embed to PURPLE
										add split field named "%{_amount::5}%" with value ":%{_amount::6}%:" to embed
										add split field named "%{_amount::7}%" with value ":%{_amount::8}%:" to embed
										set the footer of embed to footer with text "KaRin Bot Engine by IHAH"
										reply with last created embed and it in store {toophyo2::%discord id of event-user%}
										add reaction "%{_amount::6}%" to {toophyo2::%discord id of event-user%} with "{@name}"
										add reaction "%{_amount::8}%" to {toophyo2::%discord id of event-user%} with "{@name}"
										edit {toophyo::%discord id of event-user%} to show "%mention tag of event-user%, 개설한 투표가 완료되었습니다!"
										delete {toophyo::%discord id of event-user%}
										stop
						else:
							reply with "너무 빨라요!"
				else if {_amount::2} is "접두사":
					if {_amount::3} is "제거":
						if {접두사::%discord id of event-guild%} is set:
							reply with "<a:yes:707786803414958100> | 접두사가 제거되었습니다. 현재 접두사: ``카린아``"
							set {접두사::%discord id of event-guild%} to "카린아"
							stop
						else:
							reply with "<a:no:707786855143309370> | 이미 설정된 접두사가 없습니다. 현재 접두사: ``카린아``"
							stop
					if {_amount::3} is "설정":
						if {_amount::4} is set:
							if {_amount::4} is not "%{접두사::%discord id of event-guild%}%" or "카린아":
								set {접두사::%discord id of event-guild%} to "%{_amount::4}%"
								reply with "<a:yes:707786803414958100> | 접두사가 설정되었습니다.%nl%현재 접두사: ``%{접두사::%discord id of event-guild%}%``"
								stop
							else:
								reply with "<a:no:707786855143309370> | 이미 설정된 접두사에요!%nl%현재 접두사: ``%{접두사::%discord id of event-guild%}%``"
								stop
						else:
							if {접두사::%discord id of event-guild%} is set:
								reply with "> 아앗..! 명령어를 잘못 입력했어요!%nl%> ``%{접두사::%discord id of event-guild%}% 접두사 설정 [접두사]``을(를) 입력해 주세요."
							if {접두사::%discord id of event-guild%} is set:
								reply with "> 아앗..! 명령어를 잘못 입력했어요!%nl%> ``카린아 접두사 설정 [접두사]``을(를) 입력해 주세요."
				else if {_amount::2} contain "검열모드":
					if {_amount::3} contain "설정":
						if event-member has permission message manage:
							if {검열::%discord id of event-guild%} is not true:
								set {검열::%discord id of event-guild%} to true
								reply with "<a:yes:707786803414958100> 검열모드가 활성화 되었습니다."
								stop
							if {검열::%discord id of event-guild%} is true:
								set {검열::%discord id of event-guild%} to false
								reply with "<a:yes:707786803414958100> 검열모드가 비 활성화 되었습니다."
								stop
						else if event-member has permission administrator:
							if {검열::%discord id of event-guild%} is not true:
								set {검열::%discord id of event-guild%} to true
								reply with "<a:yes:707786803414958100> 검열모드가 활성화 되었습니다."
								stop
							if {검열::%discord id of event-guild%} is true:
								set {검열::%discord id of event-guild%} to false
								reply with "<a:yes:707786803414958100> 검열모드가 비 활성화 되었습니다."
								stop
						else:
							reply with "<a:no:707786855143309370> 당신은 현재 Message Manage 권한이 없습니다. 권한이 생긴 상태에서 재시도 해주세요."
				else if {_amount::2} is "시간계산":
					if {_amount::3} is "초":
						if {_amount::4} is set:
							set {_s} to {_amount::4}
							if {_s} is bigger than 60:
								set {_m} to {_s}/60
								subtract {_m}*60 from {_s}
								if {_m} is bigger than 60:
									set {_h} to {_m}/60
									subtract {_h}*60 from {_m}
									if {_h} is bigger than 24:
										set {_d} to {_h}/60
										subtract {_d}*24 from {_h}
							reply with "<a:yes:707786803414958100> 계산 결과는 이렇습니다: %{_d}%일 %{_h}%시간 %{_m}%분 %{_s}%초."
				else if {_amount::2} is "계산":
					if {_amount::5} is set:
				else if {_amount::2} is "깃헙":
					create embed:
						set the colour of the embed to GREEN
						set the description of embed to "[```카린봇 깃헙로 이동하시려면 해당 메세지를 클릭해주세요```](https://github.com/KaRinKaRin876/KRB-v2)"
						reply with last created embed
						stop
				else if {_amount::2} is "홈페이지":
					create embed:
						set the colour of the embed to GREEN
						set the description of embed to "[```홈페이지로 이동하시려면 해당 메세지를 클릭해주세요```](http://karinbot.new.so)"
						reply with last created embed
						stop
				else if {_amount::2} is "초대코드":
					if {_amount::3} is "만들기":
						if {_amount::4} is set:
							create embed:
								set the colour of the embed to GREEN
								if {_amount::5} is not set:
									set the description of embed to "[```초대링크 만들기 성공!```](https://discordapp.com/oauth2/authorize?client_id=%{_amount::4}%&permissions=0&scope=bot)"
								if {_amount::5} is set:
									set the description of embed to "[```초대링크 만들기 성공!```](https://discordapp.com/oauth2/authorize?client_id=%{_amount::4}%&permissions=%{_amount::5}%&scope=bot)"
								reply with last created embed
								stop
						else:
							reply with "Error: Client ID is not set."
							stop
					create embed:
						set the colour of the embed to GREEN
						set the description of embed to "[```초대 페이지로 이동하시려면 해당 메세지를 클릭해주세요```](https://discordapp.com/oauth2/authorize?client_id=685715386745880581&permissions=8&scope=bot)"
						reply with last created embed
						stop
				else if {_amount::2} is "버전" or "버젼" or "version":
					create embed:
						set title of the embed to "KaRin Bot Version is..."
						set the colour of the embed to GREEN
						set the description of embed to "%{version}%"
						set the footer of embed to footer with text "KaRin Bot Engine by IHAH"
						reply with last created embed
				else if {_amount::2} is "정보":
					create embed:
						set title of the embed to "KaRin Bot v2님의 정보!"
						set the colour of the embed to GREEN
						add split field named "ID" with value "%discord id of event-bot%" to embed
						add split field named "업타임" with value "%{_uptime::d}%일 %{_uptime::t}%시간 %{_uptime::m}%분 %{_uptime::s}%초" to embed
						set the footer of embed to footer with text "KaRin Bot Engine by IHAH"
						reply with last created embed
				else if {_amount::2} contain "내정보":
					if {reegestered::%discord id of event-user%} is set:
						if {_amount::3} is set:
							set {_abcd} to "%{_}%"
							replace all "카린아 내정보 상메수정" in {_abcd} with " "
							set {sangme::%discord id of event-user%} to "%{_abcd}%"
							create embed:
								set title of the embed to "%event-user% 님의 정보! (수정됨)"
								set the colour of the embed to GREEN
								add split field named "ID" with value "%discord id of event-user%" to embed
								if {point::%discord id of event-user%} is set:
									add split field named "호감도" with value "%{point::%discord id of event-user%}%" to embed
								else:
									add split field named "호감도" with value "0" to embed
								add split field named "상태 메세지" with value "```%{sangme::%discord id of event-user%}%```" to embed
								set the footer of embed to footer with text "KaRin Bot Engine by IHAH"
								reply with last created embed
						else:
							create embed:
								set title of the embed to "%event-user% 님의 정보!"
								set the colour of the embed to GREEN
								if {_amount::3} is not set:
								add split field named "ID" with value "%discord id of event-user%" to embed
								if {point::%discord id of event-user%} is set:
									add split field named "호감도" with value "%{point::%discord id of event-user%}%" to embed
								else:
									add split field named "호감도" with value "0" to embed
								add split field named "상태 메세지" with value "```%{sangme::%discord id of event-user%}%```" to embed
								set the footer of embed to footer with text "KaRin Bot Engine by IHAH"
								reply with last created embed
				else if {_amount::2} contain "ui테스트":
					create embed:
						set the colour of the embed to GREEN
						set the description of embed to "┍─────────────────%nl%│%nl%│%nl%│%nl%│%nl%│%nl%│%nl%│%nl%│%nl%┕─────────────────"
						reply with last created embed
				else if {_amount::2} contain "호감도":
					if {reegestered::%discord id of event-user%} is true:
						if {point::%discord id of event-user%} is set:
							reply with "<a:yes:707786803414958100> 저는 %mention tag of event-user% 님을 **%{point::%discord id of event-user%}%**만큼 좋아해요!"
						else:
							reply with "<a:no:707786855143309370> %mention tag of event-user% 님은 호감도가 없어요!"
					else:
						reply with "<a:no:707786855143309370> 카린아 가입 또는 카린아 regester로 가입해보세요!"
						stop
				else if {_amount::2} is "시간":
					reply with "<a:yes:707786803414958100> 현재 시간은 %now% 입니다."
					stop
				else if {_amount::2} is "배워" or "습득" or "ㅅㄷ": # TODO: 습득 안되는 버그 고치기!!!! = 완료
					if {reegestered::%discord id of event-user%} is true:
						if {_amount::3} and {_amount::4} is set:
							#set {learnban} to text from "https://pastebin.com/raw/r6bYAdyw"
							#set {learnban2::*} to {learnban} split by " "
							#if {_amount::3} is {learnban2::*}:
							if {_amount::3} is "돈" or "정보" or "내정보" or "호감도" or "서버등록해제" or "시간" or "서버등록" or "ㄷㅇㅈ" or "도와줘" or "도움말" or "문의" or "따라해" or "습득" or "ㅅㄷ" or "나루토" or "ㄴㄾ" or "ㄴㄹㅌ" or "ㄷㅇㅁ" or "뮤직" or "초대코드" or "초대링크" or "잊어" or "습득제거" or "ㅅㄷㅈㄱ" or "습득모두제거" or "ㅅㄷㅁㄷㅈㄱ" or "습득확인" or "ㅅㄷㅎㅇ" or "카린유튜브" or "명언" or "임베드따라해" or "업로드" or "후원" or "유저정보" or "가입" or "도와주거라" or "탈퇴시켜라" or "가입시켜라" or "지정상태를" or "리로드하거라" or "종료하거라" or "시작하거라" or "보아라" or "들어라" or "하거라" or "경고를" or "공지하거라":
								reply with "<a:no:707786855143309370> %mention tag of event-user%님, 그 명령어는 카린봇 기존 명령어라서 등록이 불가능해요!"
								stop
							if {_amount::3} contain "~!~" or "병신" or "씨발" or "애미" or "간나" or "좆" or "보지" or "자지" or "섹스" or "ㅆㅂ" or "ㅅㅂ" or "ㅄ" or "시발" or "새끼" or "느금마" or "ㄴㄱㅁ" or "야동" or "떽뜨" or "^^ㅣ발" or "ㅆㅂ" or "온더비치" or "온더 비치" or "nigger" or "bitch" or "sex" or "엄준식" or "ㄴㅇㅁ" or "ㅇㅁ" or "발레" or "자위" or "신음" or "지랄" or "ㅈㄹ" or "ㅇㅎㅎ" or "에헤헤" or "tq" or "tlqkf" or "ㅅㅂ" or "시발" or "씨발" or "Tlqkf" or "ㅅㅅ" or "섹스" or "꼰대" or "꼬라지" or "개떡같은" or "개같은" or "지랄" or "새끼" or "시발" or "퍽큐" or "인간말종" or "인간쓰레기" or "똥꼬" or "똥방구" or "또라이" or "자위행위" or "성행위" or "ㅗ":
								reply with "<a:no:707786855143309370> %mention tag of event-user%님, 그 명령어는 습득 시스템에서 사용 불가능한 명령어입니다!"
								stop
							else if {_amount::4} contain "~!~" or "병신" or "씨발" or "애미" or "간나" or "좆" or "보지" or "자지" or "섹스" or "ㅆㅂ" or "ㅅㅂ" or "ㅄ" or "시발" or "새끼" or "느금마" or "ㄴㄱㅁ" or "야동" or "떽뜨" or "^^ㅣ발" or "ㅆㅂ" or "온더비치" or "온더 비치" or "nigger" or "bitch" or "sex" or "엄준식" or "ㄴㅇㅁ" or "ㅇㅁ" or "발레" or "자위" or "신음" or "지랄" or "ㅈㄹ" or "ㅇㅎㅎ" or "에헤헤" or "tq" or "tlqkf" or "ㅅㅂ" or "시발" or "씨발" or "Tlqkf" or "ㅅㅅ" or "섹스" or "꼰대" or "꼬라지" or "개떡같은" or "개같은" or "지랄" or "새끼" or "시발" or "퍽큐" or "인간말종" or "인간쓰레기" or "똥꼬" or "똥방구" or "또라이" or "자위행위" or "성행위" or "ㅗ":
								reply with "<a:no:707786855143309370> %mention tag of event-user%님, 그 명령어는 습득 시스템에서 사용 불가능한 대답입니다!"
								stop
							else if {krbad::%discord id of event-user%} is "608956812636454915":
								reply with "<a:no:707786855143309370> %mention tag of event-user%님, 당신은 습득 시스템에서 제재되었습니다!"
								stop
							else:
								if {learn::%{_amount::3}%} is not set:
									if {_amount::3} contain "-":
										replace all "-" in {_amount::3} with " "
									if {_amount::4} contain "-":
										replace all "-" in {_amount::4} with " "
									add 1 to {count}
									set {learncount} to 0
									loop {learn::*}:
										add 1 to {learncount}
									if {learncount} is not between 0 and 150:
										reply with "<a:no:707786855143309370> 현재 습득된 데이터가 150개 이상을 달성하여 추가가 불가합니다! 데이터베이스를 아껴주세요!"
										stop
									set {learner::%{_amount::3}%} to "%event-user%(%discord id of event-user%)"
									set {learner2::%{_amount::3}%} to "%discord id of event-user%"
									set {learn::%{_amount::3}%} to "%{_amount::3}%~!~%{_amount::4}%~!~%{learner::%{_amount::3}%}%"
									reply with "<a:yes:707786803414958100> %mention tag of event-user%님! ``%{_amount::3}%``가 ``%{_amount::4}%``군요! 이제 알겠어요!%nl%현재 카린봇이 알고있는 지식의 갯수: %{learncount}+1% / 150"
									send "습득됨 [ ``%{_amount::3}%`` - ``%{_amount::4}%`` ] By ``%event-user%(%discord id of event-user%``" to channel with id "{@log}" with "{@name}"
									send "[습득된 명령어] %discord id of event-user%/%event-user%/%discord id of event-guild%/%event-guild%/%discord id of event-channel%/%event-channel% : %{_amount::3}% - %{amount::4}%" to console
								else:
									if {_amount::4} contain "-":
										replace all "-" in {_amount::4} with " "
									reply with "``%{_amount::3}%``은 이미 알고있어요! 하지만 ``%{_amount::4}%``도 좋은것 같네요!" 
									stop
					else:
						reply with "카린아 가입 또는 카린아 regester로 가입해보세요!"
						stop
				else if {_amount::2} is "잊히기":
					if {_amount::3} is "고정":
						if {_amount::4} is "시작":
							set {learndeleteing::%discord id of event-user%} to true
							reply with "<a:yes:707786803414958100> 습득 제거 시스템 ㅡ 고정모드가 시작되었습니다.%nl%취소하려면 ``카린아 잊히기 고정 종료``를 입력해주세요."
						else if {_amount::4} is "종료":
							set {learndeleteing::%discord id of event-user%} to false
							reply with "<a:yes:707786803414958100> 습득 제거 시스템 ㅡ 고정모드가 종료되었습니다.%nl%취소하려면 ``카린아 잊히기 고정 시작``를 입력해주세요."
						else:
							reply with "> 아앗..! 명령어를 잘못 입력했어요!%nl%> ``카린아 잊히기 고정 시작/종료`` (을)를 입력해 주세요."
				else if {_amount::2} is "잊어":
					if {_amount::3} is set:
						if {learner2::%{_amount::3}%} is "%discord id of event-user%":
							add reaction "white_check_mark" to event-message with "{@name}"
							delete {learner::%{_amount::3}%}
							delete {learner::%{_amount::3}%}
							delete {learn::%{_amount::3}%}
							if {cmdpoint::%{_amount::3}%::*} is set:
								delete {cmdpoint::%{_amount::3}%::*}
							set {learncount} to 0
							loop {learn::*}:
								add 1 to {learncount}
							reply with "현재 카린봇이 알고있는 지식의 갯수: %{learncount}-1%"
							stop
						if {learner2::%{_amount::3}%} is not "%discord id of event-user%":
							add reaction "x" to event-message with "{@name}"
					else:
						add reaction "x" to event-message with "{@name}"
				else if {_amount::2} is "내지식":
					loop {learner2::*}:
						set {learna} to loop-value
						if {learna} is "%discord id of event-user%":
							set {learnb::*} to "%{learn::}%"
				else if {_amount::2} is "습득확인" or "ㅅㄷㅎㅇ":
					if {krbad::%discord id of event-user%} is "624274923455512577":
						if {learn::*} is set:
							loop {learn::*}:
								set {_amount2::*} to loop-value split by "~!~"
								reply with "``%{_amount2::1}%`` - ``%{_amount2::2}%`` - ``%{_amount2::3}%``님이 알려준 명령어에요!"
						else:
							reply with "습득된 것이 없습니다!"
					else:
						reply with "{@b} 당신은 권한이 없습니다!"
				else if {_amount::2} contain "카린유튜브":
					reply with "https://www.youtube.com/channel/UCcX1JJpDsaROuUVHS9_vUaA"
					reply with "와! 카린유튜브!"
					stop
				else if {_amount::2} contain "습득제거" or "ㅅㄷㅈㄱ":
					if {krbad::%discord id of event-user%} is "624274923455512577":
						if {learn::%{_amount::3}%} is set:
							loop {learn::*}:
								set {_amount2::*} to loop-value split by "~!~"
								if {_amount::3} is {_amount2::1}:
									if {dc} is not true:
										set {dc} to true
										reply with "```%{_amount2::2}%```%nl%``%{_amount2::3}%``님이 알려준 명령어에요!"
										delete {learner::%{_amount::3}%}
										delete {learner2::%{_amount::3}%}
										delete {learn::%{_amount2::1}%}
										reply with "<a:yes:707786803414958100> 삭제되었습니다!"
										wait 2 ticks
										delete {dc}
										if {cmdpoint::%{_amount::3}%::*} is set:
											delete {cmdpoint::%{_amount::3}%::*}
							set {learncount} to 0
							loop {learn::*}:
								add 1 to {learncount}
							reply with "현재 카린봇이 알고있는 지식의 갯수: %{learncount}%"
							stop
						else:
							add reaction "x" to event-message with "{@name}"
					else:
						reply with "<a:no:707786855143309370> 당신은 권한이 없습니다!"
				else if {_amount::2} contain "습득모두제거" or "ㅅㄷㅁㄷㅈㄱ":
					if {krbad::%discord id of event-user%} is "624274923455512577":
						if {learn::*} is set:
							loop {learn::*}:
								set {_amount2::*} to loop-value split by "~!~"
								reply with "``%{_amount2::1}%`` - ``%{_amount2::2}%`` - ``%{_amount2::3}%``님이 알려준 명령어에요!"
							delete {learn::*}
							delete {learner::*}
							delete {learner2::*}
							reply with "<a:yes:707786803414958100> 삭제 완료!"
							stop
						else:
							add reaction "x" to event-message with "{@name}"
					else:
						reply with "<a:no:707786855143309370> 당신은 권한이 없습니다!"
				else:
					if {_amount::1} is "카린아":
						if {_amount::2} is not set:
							reply with "네, %mention tag of event-user%님! 저 여기있어요!%nl%당신이 있는 곳은 ``%event-channel%`` 이군요!"
							if {krbad::%discord id of event-user%} is set:
								reply with "```관리자: True```"
							if {krbpremium::%discord id of event-user%} is true:
								reply with "```프리미엄: ~```"
							stop
						else if {_amount::2} is not "깃헙" or "문의" or "따라해" or "뮤직" or "초대코드" or "초대링크" or "임베드따라해" or "업로드" or "후원" or "가입":
							loop {daehwa::*}:
								set {_amount2::*} to loop-value split by "~!~"
								if {_amount2::2} contain "(줄바꿈)":
									replace all "(줄바꿈)" in {_amount2::2} with "%nl%"
								if {_amount::2} is {_amount2::1}:
									if {dc} is not true:
										set {dc} to true
										reply with "%{_amount2::2}%"
										wait 2 tick
										delete {dc}
										if {cmdpoint::%{_amount::2}%::%discord id of event-user%} is not set:
											set {cmdpoint::%{_amount::2}%::%discord id of event-user%} to true
											set {pointa} to random integer between 1 and 5
											reply with "``P +%{pointa}% 획득!``"
											if {point::%discord id of event-user%} is not set:
												set {point::%discord id of event-user%} to {pointa}
											else:
												add {pointa} to {point::%discord id of event-user%}
											stop
										stop
							loop {learn::*}:
								set {_amount2::*} to loop-value split by "~!~"
								if {_amount2::2} contain "(줄바꿈)":
									replace all "(줄바꿈)" in {_amount2::2} with "%nl%"
								if {_amount::2} is {_amount2::1}:
									if {dc} is not true:
										set {dc} to true
										reply with "```%{_amount2::2}%```%nl%``%{_amount2::3}%``님이 알려준 명령어에요!"
										wait 2 tick
										delete {dc}
										if {cmdpoint::%{_amount::2}%::%discord id of event-user%} is not set:
											set {cmdpoint::%{_amount::2}%::%discord id of event-user%} to true
											set {pointa} to random integer between 1 and 5
											reply with "``P +%{pointa}% 획득!``"
											if {point::%discord id of event-user%} is not set:
												set {point::%discord id of event-user%} to {pointa}
											else:
												add {pointa} to {point::%discord id of event-user%}
											stop
										stop
							reply with "> 아앗..! 명령어를 잘못 입력했어요!%nl%> ``카린아 도와줘`` (으)로 명령어를 확인해 보시겠어요?"
							stop
			else:
				add 1 to {noserver::%discord id of event-guild%}
				if {noserver::%discord id of event-guild%} is 5 or 10 or 15 or 20 or 25 or 30 or 35 or 40 or 45 or 50 or 55 or 60 or 65 or 70 or 75 or 80 or 85 or 90 or 95 or 100:
					reply with "서버 등록을 하지 않고 명령어를 %{noserver::%discord id of event-guild%}%회 사용하셨습니다."
					if {noserver::%discord id of event-guild%} is between 1 and 19:
						reply with "서버 등록을 하지 않고 명령어를 20회 이상 사용시 서버 등록이 불가능하게 됩니다."
						stop
					if {noserver::%discord id of event-guild%} is not between 1 and 19:
						reply with "서버 등록을 하지 않고 명령어를 20회 이상 사용하셨기 때문에 서버 등록이 불가능하게 되었습니다."
						reply with "이 메세지가 보이면 봇 관리자를 불러 서버 등록 불가 상황을 해제시켜 주세요."
						delete {server::%discord id of event-guild%}
						set {antiserver::%discord id of event-guild%} to true
						stop